import { Metadata } from 'next';
import Link from 'next/link';
import ContentPageLayout, { ContentHeader } from '@/components/layout/ContentPageLayout';

export const metadata: Metadata = {
  title: 'Resurrecting Morpheus - Research Notes - Source Library',
  description:
    'How we built a 570,000-form Greek lemma table for early modern books by running a thirty-year-old parser over our own corpus — and the single wrong sigma that hid a quarter of it.',
  openGraph: {
    images: [
      {
        url: 'https://images.sourcelibrary.org/archived/adefe2d5-88a7-4595-9885-903a93abee51/391.jpg',
        alt: 'A Greek page of the Divini Platonis Opera omnia, 1590',
      },
    ],
    title: 'Resurrecting Morpheus',
    description:
      'A 570,000-form Greek lemma table for early modern books, regenerated with a thirty-year-old open-source parser — and the single wrong sigma that hid a quarter of it.',
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://images.sourcelibrary.org/archived/adefe2d5-88a7-4595-9885-903a93abee51/391.jpg',
        alt: 'A Greek page of the Divini Platonis Opera omnia, 1590',
      },
    ],
  },
  alternates: {
    canonical: '/blog/greek-lemma-table',
  },
};

export default function GreekLemmaTablePage() {
  return (
    <ContentPageLayout
      header={
        <ContentHeader
          title="Resurrecting Morpheus"
          subtitle="A 570,000-form Greek lemma table for early modern books, built with a thirty-year-old parser — and the single wrong sigma that hid a quarter of it"
          image="https://images.sourcelibrary.org/archived/adefe2d5-88a7-4595-9885-903a93abee51/391.jpg"
          imageAlt="A Greek page of the Divini Platonis Opera omnia, 1590"
        >
          <p className="text-stone-400 text-sm mt-4">9&ndash;10 August 2026 &middot; 8 min read</p>
        </ContentHeader>
      }
      bg="bg-cream"
    >
      <div className="mb-6">
        <Link
          href="/blog"
          className="inline-flex items-center gap-2 text-muted hover:text-secondary transition-colors"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          All notes
        </Link>
      </div>

      <div className="prose prose-stone max-w-none">
        <p className="lead">
          If you want a reader to tap a word in a 1590 printing of Plato and learn that
          προσέχειν is the present infinitive of προσέχω, <em>to hold to, to attend</em>, you
          need a table: every inflected form of Greek, mapped to the dictionary headword it
          belongs to. Greek is inflected enough that a single verb can wear hundreds of faces.
          Nobody types those tables by hand. They are generated by morphological analyzers, and
          for Ancient Greek there is essentially one analyzer that matters.
        </p>

        <h2>Morpheus, thirty years on</h2>
        <p>
          Morpheus is a C program written in the early 1990s for the Perseus Project. It is the
          engine behind nearly every Greek reading tool you have ever used &mdash; Perseus&rsquo;s
          word-study pages, the Alpheios reading tools, Logeion&rsquo;s parses. You hand it a
          word; it answers with every analysis it can defend: lemma, part of speech, case,
          number, tense, mood, voice. Its knowledge lives in hand-built stem and ending tables
          that encode decades of Hellenist labor.
        </p>
        <p>
          There is a ready-made dump of Morpheus output floating around &mdash; about 900,000
          analyzed forms &mdash; but it carries a NonCommercial license, and we didn&rsquo;t want
          encumbered data load-bearing in the library. The engine itself, though, is open under
          MPL-2.0, stem tables included, and the Perseids project keeps a Docker image alive. So
          instead of taking someone else&rsquo;s word list, we ran the analyzer over our own.
        </p>

        <h2>What our Greek actually looks like</h2>
        <p>
          We enumerated every distinct Greek word form across the corpus: 1,040 books, 471,544
          OCR&rsquo;d pages, from Aldine incunables to nineteenth-century editions. That yields
          <strong> 3.86 million distinct forms</strong> &mdash; far more than any classical word
          list, because early modern printing multiplies variants: ligatures, contractions,
          spelling drift, and honest OCR error. The frequency head is exactly what Greek should
          be (καί appears 5.07 million times, then δέ, τό, ἦν, τῶν), which is how you know the
          tokenizer is sane. The long tail is noise, so we kept the 989,000 forms attested at
          least three times.
        </p>
        <p>
          Morpheus speaks betacode &mdash; the 1980s convention for typing polytonic Greek in
          ASCII, where ἄνθρωπος becomes <code>a)/nqrwpos</code>. Our pipeline converts each
          Unicode form to betacode, streams it through the analyzer, and converts the answers
          back. On Apple Silicon the thirty-year-old amd64 binary runs under CPU emulation,
          which is slow, so the run is sharded across parallel containers and resumable. A few
          hours later: <strong>673,282 forms analyzed with lemmas</strong>. The forms Morpheus
          refuses are mostly what they should be &mdash; transliterated Roman names like
          Δρούσιλλαν that a classical lexicon has no business knowing.
        </p>

        <h2>The sigma that ate a quarter of the data</h2>
        <p>
          Greek writes the letter sigma two ways: σ in the middle of a word, ς at the end. Same
          letter, positional variants. Our betacode-to-Unicode converter was built from a
          reversed letter table &mdash; and because ς and σ both map to <code>s</code>, whichever
          entry came last in the table silently won the reverse direction. It was ς.
        </p>
        <p>
          Every lemma came back wearing final sigmas in the middle: προ<strong>ς</strong>έχω
          instead of προ<strong>σ</strong>έχω. Word-final sigmas looked right by accident, so
          λόγος passed every spot check. But any lemma with an <em>internal</em> sigma failed to
          match its dictionary headword, and the join between Morpheus lemmas and the lexicon
          quietly dropped 27% of the table. The headline numbers looked plausible &mdash; 73%
          joined &mdash; and the failure hid inside the remainder, mislabeled in our heads as
          &ldquo;probably proper names.&rdquo;
        </p>
        <p>
          What exposed it was not an audit but a demo: a live tap on προσέχειν in the 1590
          <em> Divini Platonis Opera omnia</em> came back empty, for a word every first-year
          student knows. One-line fix &mdash; fold ς and σ to a single letter in every key,
          on both sides of every comparison &mdash; and the join rate went from 73.3% to
          <strong> 95.1%</strong>. The lesson generalizes: when two encodings meet, normalize
          both sides with the same function, and treat &ldquo;the residue is probably
          noise&rdquo; as a claim requiring a spot check, not a shrug.
        </p>

        <h2>The dictionary side</h2>
        <p>
          The headwords come from the Liddell-Scott-Jones lexicon (9th ed., 1940) via the
          lsj9 digitization &mdash; 119,450 entries, CC&nbsp;BY&nbsp;4.0, Unicode throughout. The
          final table maps <strong>568,918 normalized Greek forms</strong> to their LSJ entries.
          Evaluated against words sampled from real OCR pages &mdash; not clean critical
          editions &mdash; lookups resolve 79.8% of the time, and the misses are dominated by
          names, abbreviations, and page furniture rather than ordinary Greek.
        </p>

        <h2>Why this is worth a note</h2>
        <p>
          Because the table was generated from <em>our</em> corpus, it knows the vocabulary our
          readers actually meet &mdash; Byzantine spellings, patristic usage, the Greek that
          appears embedded in Latin scientific books &mdash; rather than the vocabulary of a
          classical syllabus. And because the engine and its stem tables are MPL and the lexicon
          is CC&nbsp;BY, the result is unencumbered: we can serve it, share it, and ship it in
          datasets.
        </p>
        <p>
          It is also the load-bearing half of things we want next. A form-to-lemma table run in
          reverse is a concordance machine: every attestation of a lemma across two centuries of
          books, regardless of inflection &mdash; when a term enters, when it peaks, how it was
          actually used, with the passages a click away. Plain-text search cannot do this for an
          inflected language; this table can.
        </p>
        <p>
          The same build exists for Latin &mdash; 1.4 million forms generated from Lewis &amp;
          Short&rsquo;s own grammatical data, plus normalization for what early modern printing
          does to words: long-s misread as f, tilde contractions like Latinorū, the œ/æ/e
          drift. If you would like the Greek table for your own project, write to us &mdash;
          it wants to be shared.
        </p>

        <p className="text-sm text-stone-500 mt-8">
          Built on the shoulders of the Perseus Project&rsquo;s Morpheus (MPL-2.0, maintained by
          the Perseids Project) and the lsj9 digitization of Liddell-Scott-Jones (CC&nbsp;BY&nbsp;4.0).
          Gratitude to the Alpheios Project, whose reading tools first showed what tap-a-word
          Greek could feel like.
        </p>
      </div>
    </ContentPageLayout>
  );
}
