// Per-locale social share cards. A link to `/es/...` pasted into WhatsApp,
// Telegram, X or Facebook must preview in Spanish — title, description AND the
// card image, whose headline is baked into the JPEG (#4162). Before this, every
// /es page previewed under an English card reading "Unlock a New Renaissance of
// Ancient Knowledge".
//
// The card art itself is generated by scripts/one-off/generate-og-images.mjs,
// one set of four frames per locale, written to public/ as:
//   og-image-{variant}.jpg        (English — the historical, already-live names)
//   og-image-es-{variant}.jpg     (Spanish)
// src/proxy.ts rewrites the stable URLs below to the day's variant.
//
// To add a language: add its copy to COPY in the generator, run it, add the
// locale's alt text here, and add the stable path to the proxy matcher.

import type { Locale } from '@/lib/locale-path';

const SITE = 'https://sourcelibrary.org';

/** Alt text for the share card, in the card's own language. */
const OG_ALT: Record<Locale, string> = {
  en: 'Source Library: Digitizing and translating ancient texts',
  es: 'Source Library: Digitalización y traducción de textos antiguos',
  la: 'Source Library: textus antiqui photographice descripti et conversi',
  nl: 'Source Library: oude teksten gedigitaliseerd en vertaald',
  zh: 'Source Library：古籍数字化与翻译',
};

/** Prefixed locales whose share-card art exists under `public/` (`og-image-<iso>-*.jpg`). */
const OWN_CARD_ART: Locale[] = ['es'];

/** `og:locale` value for a locale. */
export const OG_LOCALE: Record<Locale, string> = {
  en: 'en_US',
  es: 'es_ES',
  la: 'la_VA',
  nl: 'nl_NL',
  zh: 'zh_CN',
};

/**
 * The stable share-card URL for a locale. English keeps the unprefixed path:
 * it is quoted in the wild and cached by every crawler that has ever seen a
 * sourcelibrary.org link.
 */
export function siteOgImageUrl(lang: Locale): string {
  // Latin has no card art of its own yet (#6254), so it shares the English
  // card rather than point at a file that does not exist. Add the locale here
  // on the day `scripts/one-off/generate-og-images.mjs` has been run for it
  // and `src/proxy.ts` rewrites its URL.
  return OWN_CARD_ART.includes(lang) ? `${SITE}/og-image-${lang}.jpg` : `${SITE}/og-image.jpg`;
}

/**
 * A ready-made entry for `openGraph.images` / `twitter.images`. Dimensions are
 * the DISPLAY size crawlers are told about; the files themselves are 2×
 * (2400×1260) so the card stays sharp on a retina timeline.
 */
export function siteOgImage(lang: Locale): { url: string; width: number; height: number; alt: string } {
  return { url: siteOgImageUrl(lang), width: 1200, height: 630, alt: OG_ALT[lang] };
}

/** Alt text alone, for callers that build their own image entry. */
export function siteOgAlt(lang: Locale): string {
  return OG_ALT[lang];
}
