import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Piece Review — Rithmomachia',
  robots: { index: false },
};

const BLOB = 'https://3kwioilsplnmnkv8.public.blob.vercel-storage.com/rithmomachia';

const grids = [0, 1, 2, 3].map(i => `${BLOB}/review/grid_0${i}.png`);

const extractions = {
  circle: ['left', 'center', 'right'].map(pos => ({
    label: pos,
    url: `${BLOB}/review/circle_${pos}.png`,
  })),
  triangle: ['left', 'center', 'right'].map(pos => ({
    label: pos,
    url: `${BLOB}/review/triangle_${pos}.png`,
  })),
  square: ['left', 'center', 'right'].map(pos => ({
    label: pos,
    url: `${BLOB}/review/square_${pos}.png`,
  })),
};

const finals = {
  circle: {
    light: `${BLOB}/pieces/circle_light.png`,
    dark: `${BLOB}/pieces/circle_dark.png`,
  },
  triangle: {
    light: `${BLOB}/pieces/triangle_light.png`,
    dark: `${BLOB}/pieces/triangle_dark.png`,
  },
  square: {
    light: `${BLOB}/pieces/square_light.png`,
    dark: `${BLOB}/pieces/square_dark.png`,
  },
};

export default function PieceReviewPage() {
  return (
    <div style={{ maxWidth: 1200, margin: '0 auto', padding: '2rem', fontFamily: 'var(--font-sans)', color: '#1a1612', background: '#fdfcf9' }}>
      <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: '2rem', marginBottom: '0.5rem' }}>
        Rithmomachia Piece Review
      </h1>
      <p style={{ color: '#6b6560', marginBottom: '2rem' }}>
        Pick your preferred pieces for the game. All generated by Wan2.6-t2i with copperplate engraving prompt.
      </p>

      {/* Section 1: Source Grids */}
      <section style={{ marginBottom: '3rem' }}>
        <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginBottom: '1rem', borderBottom: '1px solid #e8e4dc', paddingBottom: '0.5rem' }}>
          1. Source Grids (pick your favorite)
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem' }}>
          {grids.map((url, i) => (
            <div key={i} style={{ border: '1px solid #e8e4dc', borderRadius: 8, overflow: 'hidden', background: '#fff' }}>
              <div style={{ padding: '0.5rem 1rem', background: '#f5f0e8', fontWeight: 600, fontSize: '0.875rem' }}>
                Grid {i} {i === 0 ? '(my pick)' : ''}
              </div>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={url} alt={`Grid ${i}`} style={{ width: '100%', display: 'block' }} />
            </div>
          ))}
        </div>
      </section>

      {/* Section 2: Extracted Pieces from Grid 0 */}
      <section style={{ marginBottom: '3rem' }}>
        <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginBottom: '1rem', borderBottom: '1px solid #e8e4dc', paddingBottom: '0.5rem' }}>
          2. Extracted Pieces (from Grid 0 — left / center / right column)
        </h2>
        {(['circle', 'triangle', 'square'] as const).map(shape => (
          <div key={shape} style={{ marginBottom: '2rem' }}>
            <h3 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.125rem', marginBottom: '0.75rem', textTransform: 'capitalize' }}>
              {shape}s
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
              {extractions[shape].map(({ label, url }) => (
                <div key={label} style={{ border: '1px solid #e8e4dc', borderRadius: 8, overflow: 'hidden', background: '#fff' }}>
                  <div style={{ padding: '0.5rem 1rem', background: '#f5f0e8', fontWeight: 600, fontSize: '0.875rem' }}>
                    {label}
                    {(shape === 'circle' && label === 'center') ||
                     (shape === 'triangle' && label === 'left') ||
                     (shape === 'square' && label === 'right') ? ' (my pick)' : ''}
                  </div>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={url} alt={`${shape} ${label}`} style={{ width: '100%', display: 'block' }} />
                </div>
              ))}
            </div>
          </div>
        ))}
      </section>

      {/* Section 3: Processed Finals */}
      <section style={{ marginBottom: '3rem' }}>
        <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginBottom: '1rem', borderBottom: '1px solid #e8e4dc', paddingBottom: '0.5rem' }}>
          3. Processed Finals (light = even/white side, dark = odd/black side)
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1.5rem' }}>
          {(['circle', 'triangle', 'square'] as const).map(shape => (
            <div key={shape}>
              <h3 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.125rem', marginBottom: '0.75rem', textTransform: 'capitalize', textAlign: 'center' }}>
                {shape}
              </h3>
              <div style={{ display: 'flex', gap: '0.75rem' }}>
                <div style={{ flex: 1, border: '1px solid #e8e4dc', borderRadius: 8, overflow: 'hidden', background: '#f5f0e8' }}>
                  <div style={{ padding: '0.25rem 0.5rem', fontWeight: 600, fontSize: '0.75rem', textAlign: 'center' }}>
                    Light (even)
                  </div>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={finals[shape].light} alt={`${shape} light`} style={{ width: '100%', display: 'block' }} />
                </div>
                <div style={{ flex: 1, border: '1px solid #e8e4dc', borderRadius: 8, overflow: 'hidden', background: '#2a1f15' }}>
                  <div style={{ padding: '0.25rem 0.5rem', fontWeight: 600, fontSize: '0.75rem', textAlign: 'center', color: '#e8dfd0' }}>
                    Dark (odd)
                  </div>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img src={finals[shape].dark} alt={`${shape} dark`} style={{ width: '100%', display: 'block' }} />
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Section 4: In Context */}
      <section style={{ marginBottom: '3rem' }}>
        <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginBottom: '1rem', borderBottom: '1px solid #e8e4dc', paddingBottom: '0.5rem' }}>
          4. At Game Size (80px, with number overlay)
        </h2>
        <p style={{ color: '#6b6560', marginBottom: '1rem', fontSize: '0.875rem' }}>
          This is how pieces will look on the board. Numbers will be overlaid via SVG text.
        </p>
        <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap', padding: '2rem', background: '#e8e0d0', borderRadius: 8 }}>
          {(['circle', 'triangle', 'square'] as const).map(shape => (
            <div key={shape} style={{ display: 'flex', gap: '1rem' }}>
              <div style={{ position: 'relative', width: 80, height: 80 }}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={finals[shape].light} alt="" style={{ width: 80, height: 80, borderRadius: 4 }} />
                <span style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', fontFamily: 'var(--font-serif)', fontWeight: 700, fontSize: 18, color: '#1a1612', textShadow: '0 0 3px rgba(240,235,224,0.8)' }}>
                  {shape === 'circle' ? '6' : shape === 'triangle' ? '42' : '153'}
                </span>
              </div>
              <div style={{ position: 'relative', width: 80, height: 80 }}>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={finals[shape].dark} alt="" style={{ width: 80, height: 80, borderRadius: 4 }} />
                <span style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', fontFamily: 'var(--font-serif)', fontWeight: 700, fontSize: 18, color: '#e8dfd0', textShadow: '0 0 3px rgba(26,22,18,0.8)' }}>
                  {shape === 'circle' ? '5' : shape === 'triangle' ? '56' : '120'}
                </span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Section 5: What's Missing */}
      <section style={{ marginBottom: '2rem' }}>
        <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.5rem', marginBottom: '1rem', borderBottom: '1px solid #e8e4dc', paddingBottom: '0.5rem' }}>
          5. Still Needed
        </h2>
        <ul style={{ paddingLeft: '1.5rem', color: '#444' }}>
          <li>Pyramid piece (stacked layers — can compose from existing or generate new)</li>
          <li>Decide: should we re-generate from a different grid or different prompts?</li>
          <li>Number placement/styling — serif italic? plain? engraved look?</li>
        </ul>
      </section>
    </div>
  );
}
