'use client';

import { useEffect, useRef, useState } from 'react';
import { ToneEngine } from './audio';
import { LabCard, PlayToggle, Readout } from './LabCard';

const F1 = 660;

/**
 * Station V — Tartini's third tone.
 *
 * Play two loud pure tones and a third, lower tone appears that no
 * instrument is producing — the difference tone (f1 − f2), generated by the
 * ear itself. Tartini built his theory of harmony on it (1754). Slide the
 * second tone and listen underneath for the ghost that follows.
 */
export default function TartiniDemo() {
  const [playing, setPlaying] = useState(false);
  const [f2, setF2] = useState(440);
  const engineRef = useRef<ToneEngine | null>(null);

  const ghost = F1 - f2;

  useEffect(() => {
    const e = engineRef.current;
    if (!e || !playing) return;
    e.setVoice('t1', F1, 0.55, 'sine');
    e.setVoice('t2', f2, 0.55, 'sine');
  }, [playing, f2]);

  useEffect(() => () => { engineRef.current?.dispose(); }, []);

  const toggle = () => {
    if (playing) {
      engineRef.current?.stopAllVoices();
      engineRef.current?.suspend();
      setPlaying(false);
      return;
    }
    if (!engineRef.current) engineRef.current = new ToneEngine();
    engineRef.current.ensure();
    setPlaying(true);
  };

  const preview = async () => {
    if (!engineRef.current) engineRef.current = new ToneEngine();
    engineRef.current.ensure();
    await engineRef.current.playTones([Math.max(30, ghost)], 900, 'sine', 0.5);
  };

  return (
    <LabCard
      title="Station V — The tone nobody is playing"
      headerRight={<PlayToggle playing={playing} onClick={toggle} label="Play the two tones" />}
      caption="Turn the volume up a little and listen below the two tones for a third, buzzing bass note — the difference tone your ear manufactures. Slide the second tone and the ghost slides with it, at exactly f₁ − f₂."
      sourceHref="/book/trattato-di-musica-secondo-la-vera-scienza-dell-armonia-tartini"
      sourceLabel="Giuseppe Tartini, Trattato di musica (1754)"
    >
      <label className="block">
        <span className="flex items-baseline justify-between text-sm text-secondary mb-1">
          <span>Second tone (first stays {F1} Hz)</span>
          <span className="font-mono text-primary">{f2.toFixed(0)} Hz</span>
        </span>
        <input
          type="range" min={440} max={650} step={1} value={f2}
          onChange={(e) => setF2(Number(e.target.value))}
          className="w-full accent-[var(--accent-rust,#a8503c)]"
          aria-label="Second tone frequency in hertz"
        />
      </label>

      <div className="mt-4 grid grid-cols-3 gap-3">
        <Readout label="Tone 1" value={`${F1} Hz`} />
        <Readout label="Tone 2" value={`${f2.toFixed(0)} Hz`} />
        <Readout label="The ghost" value={`${ghost.toFixed(0)} Hz`} note="f₁ − f₂ — made by your ear" />
      </div>

      <button
        onClick={preview}
        className="mt-4 px-3 py-1.5 rounded-full text-xs border border-border-light text-muted hover:text-secondary hover:border-stone-300"
      >
        Preview what to listen for (plays {Math.max(30, ghost).toFixed(0)} Hz aloud)
      </button>
    </LabCard>
  );
}
