'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ToneEngine } from './audio';
import { LabCard, PlayToggle, Readout, Chip } from './LabCard';

const F1 = 660;

const TARTINI_PLATE =
  'https://images.sourcelibrary.org/gallery/6990585617295890441358e0/699058571729589044135991-0.jpg?v=17816616026';

/**
 * Simple consonances against the fixed 660 Hz voice. (Not a transcription
 * of the p177 examples — those work through major/minor-tone cases; these
 * are the textbook dyads of the same phenomenon.) For any m:n dyad on a
 * common fundamental g (f1 = m·g, f2 = n·g with m = n+1), the difference
 * tone IS g: the bass the consonance implies. That is his whole theory.
 */
const FIGURES = [
  { name: 'fifth, 3:2', f2: 440 },
  { name: 'fourth, 4:3', f2: 495 },
  { name: 'major third, 5:4', f2: 528 },
  { name: 'minor third, 6:5', f2: 550 },
];

const NOTE_NAMES = ['C', 'C♯', 'D', 'D♯', 'E', 'F', 'F♯', 'G', 'G♯', 'A', 'A♯', 'B'];

function noteName(f: number): string {
  if (f < 20) return '—';
  const midi = 69 + 12 * Math.log2(f / 440);
  const nearest = Math.round(midi);
  const octave = Math.floor(nearest / 12) - 1;
  return `${NOTE_NAMES[((nearest % 12) + 12) % 12]}${octave}`;
}

/** Nearest small-integer ratio m:n (n < m ≤ 9) within 10 cents, else null. */
function nearestSimpleRatio(f1: number, f2: number): { m: number; n: number } | null {
  let best: { m: number; n: number; err: number } | null = null;
  for (let m = 2; m <= 9; m++) {
    for (let n = 1; n < m; n++) {
      const err = Math.abs(1200 * Math.log2((f1 / f2) / (m / n)));
      if (err < 10 && (!best || err < best.err)) best = { m, n, err };
    }
  }
  return best && { m: best.m, n: best.n };
}

/**
 * Station V — Tartini's third tone.
 *
 * Play two loud pure tones and a third, lower tone appears that no
 * instrument is producing — the difference tone (f1 − f2), generated by the
 * ear itself. Tartini built his theory of harmony on it (1754): the ghost
 * is the BASS the consonance implies, and his engraved figures notate it
 * as a real note with a name. So does this station.
 */
export default function TartiniDemo() {
  const [playing, setPlaying] = useState(false);
  const [f2, setF2] = useState(440);
  const engineRef = useRef<ToneEngine | null>(null);

  const ghost = F1 - f2;

  useEffect(() => {
    const e = engineRef.current;
    if (!e || !playing) return;
    e.setVoice('t1', F1, 0.55, 'sine');
    e.setVoice('t2', f2, 0.55, 'sine');
  }, [playing, f2]);

  useEffect(() => () => { engineRef.current?.dispose(); }, []);

  const toggle = () => {
    if (playing) {
      engineRef.current?.stopAllVoices();
      engineRef.current?.suspend();
      setPlaying(false);
      return;
    }
    if (!engineRef.current) engineRef.current = new ToneEngine();
    engineRef.current.ensure();
    setPlaying(true);
  };

  const playFigure = (freq: number) => {
    setF2(freq);
    if (!engineRef.current) engineRef.current = new ToneEngine();
    engineRef.current.ensure();
    setPlaying(true);
  };

  const preview = async () => {
    if (!engineRef.current) engineRef.current = new ToneEngine();
    engineRef.current.ensure();
    await engineRef.current.playTones([Math.max(30, ghost)], 900, 'sine', 0.5);
  };

  // Precomputed for JSX (React Compiler hoists member access above guards).
  const simple = nearestSimpleRatio(F1, f2);
  const isFundamental = simple !== null && simple.m - simple.n === 1;
  const ratioLine = simple === null
    ? 'Between his figures — the ghost wanders with the slider.'
    : isFundamental
      ? `${simple.m}:${simple.n} — so ${F1} = ${simple.m} × ${ghost.toFixed(0)} and ${f2.toFixed(0)} = ${simple.n} × ${ghost.toFixed(0)}: the ghost is the fundamental both tones share, the bass the consonance implies. His figures notate exactly this.`
      : `${simple.m}:${simple.n} — the ghost lands on a harmonic of the implied bass.`;

  return (
    <LabCard
      title="Station V — The tone nobody is playing"
      headerRight={<PlayToggle playing={playing} onClick={toggle} label="Play the two tones" />}
      caption="Turn the volume up a little and listen below the two tones for a third, buzzing bass note — the difference tone your ear manufactures. Slide the second tone and the ghost slides with it, at exactly f₁ − f₂."
      sourceHref="/book/trattato-di-musica-secondo-la-vera-scienza-dell-armonia-tartini"
      sourceLabel="Giuseppe Tartini, Trattato di musica (1754)"
    >
      <label className="block">
        <span className="flex items-baseline justify-between text-sm text-secondary mb-1">
          <span>Second tone (first stays {F1} Hz)</span>
          <span className="font-mono text-primary">{f2.toFixed(0)} Hz</span>
        </span>
        <input
          type="range" min={440} max={650} step={1} value={f2}
          onChange={(e) => setF2(Number(e.target.value))}
          className="w-full accent-[var(--accent-rust,#a8503c)]"
          aria-label="Second tone frequency in hertz"
        />
      </label>

      <div className="mt-4 grid grid-cols-3 gap-3">
        <Readout label="Tone 1" value={`${F1} Hz`} note={noteName(F1)} />
        <Readout label="Tone 2" value={`${f2.toFixed(0)} Hz`} note={noteName(f2)} />
        <Readout label="The ghost" value={`${ghost.toFixed(0)} Hz`} note={`≈ ${noteName(ghost)} — made by your ear`} />
      </div>
      <p className="mt-2 text-xs text-muted">{ratioLine}</p>

      <button
        onClick={preview}
        className="mt-4 px-3 py-1.5 rounded-full text-xs border border-border-light text-muted hover:text-secondary hover:border-stone-300"
      >
        Preview what to listen for (plays {Math.max(30, ghost).toFixed(0)} Hz aloud)
      </button>

      <div className="mt-5 pt-4 border-t border-border-light">
        <p className="text-[11px] uppercase tracking-wider text-muted mb-2">
          The phenomenon he engraved, playable
        </p>
        <div className="md:flex md:gap-4">
          <Link
            href="/book/trattato-di-musica-secondo-la-vera-scienza-dell-armonia-tartini?page=177"
            className="block md:w-64 shrink-0 rounded overflow-hidden border border-border-light hover:border-stone-300"
          >
            <img
              src={TARTINI_PLATE}
              alt="Tartini's engraved examples: pairs of notes on staves with the words 'terzo suono' beneath each notated third tone"
              className="w-full h-auto"
              loading="lazy"
            />
          </Link>
          <div className="mt-3 md:mt-0">
            <p className="text-xs text-secondary mb-2">
              Tartini engraves the ghost as a real note — <em>terzo suono</em> written under each
              worked dyad on this page. These presets put the slider on simple consonances so you
              can hear the bass his theory predicts:
            </p>
            <div className="flex flex-wrap gap-1.5">
              {FIGURES.map((fig) => (
                <Chip key={fig.name} active={Math.abs(f2 - fig.f2) < 2} onClick={() => playFigure(fig.f2)}>
                  {fig.name}
                </Chip>
              ))}
            </div>
          </div>
        </div>
      </div>
    </LabCard>
  );
}
