import { Metadata } from 'next';
import { notFound, redirect } from 'next/navigation';
import { getTenantContext } from '@/lib/tenant-context';
import { stripEditorialWrappers } from '@/lib/strip-editorial-wrappers';
// `cache()`d in its own module: generateMetadata, the shell below, and the
// (reader) group layout's visibility gate all read it, so one round trip
// serves the whole request.
import { getPageData } from './page-data';
import { type Locale } from '@/lib/locale-path';
import { READER_STRINGS } from '@/lib/book-i18n';
import { localizedTitle, hasLocalizedEdition } from '@/lib/localized';

export const preferredRegion = 'fra1';

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{ id: string; pageId: string }>;
}

export async function generateMetadata({ params, lang = 'en' }: LayoutProps & { lang?: Locale }): Promise<Metadata> {
  const { id, pageId } = await params;
  const rs = READER_STRINGS[lang];
  const ctx = await getTenantContext();
  const { book, page } = await getPageData(id, pageId, ctx?.id ?? undefined);

  if (!book || !page) {
    // Self-referential canonical so this URL isn't seen as a duplicate of '/'
    // (inherited root canonical).
    return {
      title: 'Page Not Found - Source Library',
      robots: { index: false, follow: true },
      alternates: { canonical: `/book/${id}/page/${pageId}` },
    };
  }

  const bookTitle = localizedTitle(book as Parameters<typeof localizedTitle>[0], lang);
  const pageNum = page.page_number;
  const ogBookTitle = book.published ? `${bookTitle} (${book.published})` : bookTitle;
  const title = rs.metaTitle(ogBookTitle, pageNum);

  // Use translation excerpt if available, otherwise OCR excerpt. Strip editorial
  // wrapper blocks first so <meta>/<summary>/… prose never lands in the OG
  // description / search snippet (#2232 invariant).
  const textContent = stripEditorialWrappers(page.translation?.data || page.ocr?.data || '').trim();
  const excerpt = textContent.length > 200
    ? textContent.substring(0, 197) + '...'
    : textContent;

  // The excerpt is the page's own text in the reader's language; the sentence
  // around it follows the locale. An untranslated book keeps its English frame.
  const description = excerpt
    ? `${rs.metaPageOf(pageNum, bookTitle)} — ${book.author}. ${excerpt}`
    : `Page ${pageNum} of "${bookTitle}" by ${book.author}${book.published ? ` (${book.published})` : ''}. Digitized from the original ${book.language || 'manuscript'}.`;

  // Always use slug for canonical URL, even if accessed via hex ObjectId
  const bookPath = (book as unknown as { slug?: string }).slug || id;
  const pageUrl = `/book/${bookPath}/page/${pageId}`;

  // Reader pages are noindex by default (they outnumber book URLs ~100:1 and
  // are thin on their own). Demand-proven pages — read >=5 in the rolling 90d
  // window, or translated first-translations — are opened to indexing by
  // scripts/seo/flag-indexable-pages.mjs (issue #2688), which sets
  // `seo_indexable` on the page doc. Canonical is already self-referential, so
  // an opened page indexes on its own URL. See robots.ts (crawling stays open
  // for all; this gate controls *indexing*).
  const indexable = (page as unknown as { seo_indexable?: boolean }).seo_indexable === true;

  return {
    title: `${title} - Source Library`,
    description,
    robots: { index: indexable, follow: true },
    alternates: {
      canonical: pageUrl,
    },
    openGraph: {
      title,
      description,
      type: 'article',
      siteName: 'Source Library',
      locale: 'en_US',
      url: pageUrl,
      // OG image generated by opengraph-image.tsx (branded 1200x630 card)
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      // Twitter image generated by opengraph-image.tsx
    },
  };
}

export default async function PageLayout({ children, params, lang = 'en' }: LayoutProps & { lang?: Locale }) {
  // Resolve existence HERE, in the shell, rather than leaving it to page.tsx.
  //
  // This segment has a loading.tsx and deliberately keeps it — the reader is
  // the one route where the skeleton earns its place, on every page turn. But
  // a loading.tsx wraps its page.tsx in an automatic <Suspense>, so Next.js
  // flushes the 200 shell the moment the page's data fetch suspends, before
  // page.tsx's notFound() runs. The status is committed by then and notFound()
  // can only swap the body — the soft-404 documented in CLAUDE.md and fixed on
  // sibling routes in #3277 and #3376.
  //
  // A layout sits ABOVE that boundary, so awaiting here still sets a real 404
  // and the skeleton is untouched.
  //
  // The condition is deliberately a strict SUBSET of page.tsx's four notFound()
  // cases: missing page, missing book, and (inside getPageData) a page whose
  // book_id doesn't match the book in the URL. The hidden-book gate CANNOT live
  // here — this layout also wraps page/[pageId]/preview, the auth-gated editor
  // route that renders hidden books on purpose (allowHidden), and a layout gets
  // no signal about which child segment is rendering. It lives one level down in
  // (reader)/layout.tsx, a URL-neutral route group that /preview sits outside
  // of (#3385).
  const { id, pageId } = await params;
  const ctx = await getTenantContext();
  const { book, page } = await getPageData(id, pageId, ctx?.id ?? undefined);
  if (!book || !page) notFound();

  // A localized URL is a promise the page is in that language, so a book with
  // no edition in it has no localized reader URL — 307 to the English one.
  //
  // This MUST live in the layout, not in page.tsx. The (reader) segment has a
  // loading.tsx, so the page is wrapped in an automatic <Suspense> and the 200
  // shell flushes before the page's code runs: a redirect() down there degrades
  // into a client-side meta-refresh (#4036), which a crawler will happily index.
  // Measured — the page-level version returned 200 with NEXT_REDIRECT in the
  // body. The layout sits above that boundary, so this is a real HTTP 307.
  //
  // 307, not 308: the day the book is translated the URL must start working.
  // `?? false` because PAGE_META_PROJECTION asks for BOTH inputs — the
  // `pages_translated_es` counter and `language` — so an absent value means the
  // book has no edition in the language rather than "could not tell". If that
  // projection ever drops `language`, every natively-Spanish book starts
  // redirecting away from its own /es reader.
  if (lang !== 'en' && (hasLocalizedEdition(book as unknown as Record<string, unknown>, lang) ?? false) === false) {
    redirect(`/book/${(book as unknown as { slug?: string }).slug || id}/page/${pageId}`);
  }

  return children;
}
