import { Metadata } from 'next';
import { getReadDb } from '@/lib/mongodb';
import { findTenantBookByIdOrSlug } from '@/lib/tenant-book-lookup';
import { Book, Page } from '@/lib/types';

export const preferredRegion = 'fra1';

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{ tenant: string; id: string; pageId: string }>;
}

// Only fetch the fields needed for metadata — skip index, reading_summary, etc.
const BOOK_META_PROJECTION = {
  _id: 0, id: 1, slug: 1, title: 1, display_title: 1, author: 1, published: 1, language: 1,
};
const PAGE_META_PROJECTION = {
  _id: 0, id: 1, book_id: 1, page_number: 1, photo: 1,
  'translation.data': 1, 'ocr.data': 1,
};

async function getPageData(tenantSlug: string, bookId: string, pageId: string): Promise<{ book: Book | null; page: Page | null }> {
  try {
    const db = await getReadDb();
    const [bookResult, page] = await Promise.all([
      findTenantBookByIdOrSlug(db, tenantSlug, bookId, BOOK_META_PROJECTION),
      db.collection('pages').findOne({ id: pageId }, { projection: PAGE_META_PROJECTION }),
    ]);

    const book = (bookResult?.book ?? null) as unknown as Book | null;
    if (book && page) {
      const scopedBookId = (book.id || (book as any)._id?.toString()) as string;
      if ((page as any).book_id && (page as any).book_id !== scopedBookId) {
        return { book: null, page: null };
      }
    }

    return {
      book,
      page: page as unknown as Page | null,
    };
  } catch {
    return { book: null, page: null };
  }
}

export async function generateMetadata({ params }: LayoutProps): Promise<Metadata> {
  const { tenant, id, pageId } = await params;
  const { book, page } = await getPageData(tenant, id, pageId);

  if (!book || !page) {
    // Self-referential canonical so this URL isn't seen as a duplicate of '/'
    // (inherited root canonical). Per-page URLs are already noindex via the
    // page-level metadata export.
    return {
      title: 'Page Not Found - Source Library',
      alternates: { canonical: `/book/${id}/page/${pageId}` },
    };
  }

  const bookTitle = book.display_title || book.title;
  const pageNum = page.page_number;
  const ogBookTitle = book.published ? `${bookTitle} (${book.published})` : bookTitle;
  const title = `${ogBookTitle} - Page ${pageNum}`;

  // Use translation excerpt if available, otherwise OCR excerpt
  const textContent = page.translation?.data || page.ocr?.data || '';
  const excerpt = textContent.length > 200
    ? textContent.substring(0, 197) + '...'
    : textContent;

  const description = excerpt
    ? `Page ${pageNum} of "${bookTitle}" by ${book.author}. ${excerpt}`
    : `Page ${pageNum} of "${bookTitle}" by ${book.author}${book.published ? ` (${book.published})` : ''}. Digitized from the original ${book.language || 'manuscript'}.`;

  // Always use slug for canonical URL, even if accessed via hex ObjectId
  const bookPath = (book as unknown as { slug?: string }).slug || id;
  const pageUrl = `/book/${bookPath}/page/${pageId}`;

  return {
    title: `${title} - Source Library`,
    description,
    alternates: {
      canonical: pageUrl,
    },
    openGraph: {
      title,
      description,
      type: 'article',
      siteName: 'Source Library',
      locale: 'en_US',
      url: pageUrl,
      // OG image generated by opengraph-image.tsx (branded 1200x630 card)
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      // Twitter image generated by opengraph-image.tsx
    },
  };
}

export default async function PageLayout({ children }: LayoutProps) {
  return children;
}
