'use client';

import { useState, useEffect, useRef } from 'react';
import { History, RotateCcw, X, ChevronDown, Pencil } from 'lucide-react';
import { AuthCheck } from '@/components/auth/AuthCheck';
import type { PageRevision } from '@/lib/page-revisions';

interface RevisionHistoryProps {
  pageId: string;
  field: 'ocr' | 'translation';
  currentSource?: string;
  editedBy?: string;
  editedAt?: Date | string;
  model?: string;
}

function formatDate(date: string | Date) {
  const d = new Date(date);
  const now = new Date();
  const diffMs = now.getTime() - d.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return 'Today ' + d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  if (diffDays === 1) return 'Yesterday';
  if (diffDays < 7) return `${diffDays}d ago`;
  return d.toLocaleDateString([], { month: 'short', day: 'numeric', year: d.getFullYear() !== now.getFullYear() ? 'numeric' : undefined });
}

function truncate(text: string, len: number) {
  if (text.length <= len) return text;
  return text.slice(0, len) + '...';
}

// Friendly display names for the per-page AI model badge. Gemini ids fall through
// to the old gemini-/‑preview stripping; Claude ids get a clean short name.
const MODEL_LABELS: Record<string, string> = {
  'claude-opus-4-8': 'Opus 4.8',
  'claude-opus-4-8[1m]': 'Opus 4.8',
  'claude-sonnet-5': 'Sonnet 5',
  'claude-haiku-4-5': 'Haiku 4.5',
};
function formatModel(model: string) {
  return MODEL_LABELS[model] ?? model.replace('gemini-', '').replace('-preview', '');
}

const AI_TINT = { bg: 'rgba(124, 93, 181, 0.1)', color: 'var(--accent-violet)' };
const HUMAN_TINT = { bg: 'rgba(139, 154, 125, 0.15)', color: 'var(--accent-sage)' };
const SOURCE_TINT = { bg: 'rgba(201, 168, 108, 0.15)', color: 'var(--accent-gold-dark)' };

function SourceBadge({ source }: { source: string }) {
  const styles: Record<string, { bg: string; color: string; label: string; title: string }> = {
    ai: { ...AI_TINT, label: 'AI', title: 'Generated by a model' },
    batch_api: { ...AI_TINT, label: 'Batch', title: 'Generated by a model, through the batch API' },
    batch_api_reconcile: { ...AI_TINT, label: 'Batch', title: 'Generated by a model, through the batch API' },
    'ai-pivot-en': { ...AI_TINT, label: 'AI ← EN', title: 'Translated by a model FROM our English translation, not from the page' },
    manual: { ...HUMAN_TINT, label: 'Manual', title: 'Written or corrected by an editor' },
    contributor: { ...SOURCE_TINT, label: 'Contrib', title: 'Written or corrected by a contributor' },
    // Not a translation of ours at all: the leaf's own column, already in this
    // language. Tinted with the human colours because the words are a
    // sixteenth- or seventeenth-century translator's, not a model's.
    'source-column': {
      ...SOURCE_TINT,
      label: 'On the leaf',
      title: 'Not our translation — this is the column of the page that is already in this language, transcribed from the scan. The words are the historical translator’s; the period spelling is theirs.',
    },
  };
  // An UNRECOGNISED provenance is shown as unrecognised. Falling through to "AI"
  // was the quiet version of the mistake this badge exists to prevent: it labels
  // words a model did not write, and it would have shown a 1701 Spanish column
  // as machine output.
  const s = styles[source] || {
    bg: 'rgba(0,0,0,0.05)',
    color: 'var(--text-muted)',
    label: truncate(source, 14),
    title: `Provenance recorded as "${source}" — not a value this reader knows how to describe.`,
  };

  return (
    <span
      className="px-1.5 py-0.5 rounded text-[10px] font-medium"
      style={{ background: s.bg, color: s.color }}
      title={s.title}
    >
      {s.label}
    </span>
  );
}

export default function RevisionHistory({ pageId, field, currentSource, editedBy, editedAt, model }: RevisionHistoryProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [revisions, setRevisions] = useState<PageRevision[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [restoring, setRestoring] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!isOpen) return;
    setLoading(true);
    fetch(`/api/pages/${pageId}/revisions?field=${field}&limit=20`)
      .then(r => r.json())
      .then(data => {
        setRevisions(data.revisions || []);
        setTotal(data.total || 0);
      })
      .catch(() => setRevisions([]))
      .finally(() => setLoading(false));
  }, [isOpen, pageId, field]);

  // Close on outside click
  useEffect(() => {
    if (!isOpen) return;
    function handleClick(e: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    }
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [isOpen]);

  async function handleRestore(revisionId: string) {
    setRestoring(revisionId);
    try {
      const res = await fetch(`/api/pages/${pageId}/revisions/${revisionId}/restore`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ restoredBy: 'User' }),
      });
      if (res.ok) {
        // Reload the page to show restored content
        window.location.reload();
      }
    } catch {
      // ignore
    } finally {
      setRestoring(null);
    }
  }

  return (
    <div className="relative" ref={dropdownRef}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-1.5 px-2 py-1 rounded text-[10px] font-medium transition-colors hover:bg-stone-100"
        style={{ color: 'var(--text-muted)' }}
        title={`${field === 'ocr' ? 'OCR' : 'Translation'} source & revision history`}
      >
        {currentSource === 'manual' || currentSource === 'contributor' ? (
          <>
            <Pencil className="w-3 h-3" style={{ color: currentSource === 'contributor' ? 'var(--accent-gold-dark)' : 'var(--accent-sage)' }} />
            <span style={{ color: currentSource === 'contributor' ? 'var(--accent-gold-dark)' : 'var(--accent-sage)' }}>
              {editedBy || (currentSource === 'contributor' ? 'Contrib' : 'Edited')}
            </span>
            {editedAt && (
              <span style={{ color: 'var(--text-faint)' }}>{formatDate(editedAt)}</span>
            )}
          </>
        ) : (
          <>
            <SourceBadge source={currentSource || 'ai'} />
            {model && (
              <span style={{ color: 'var(--text-faint)' }}>
                {formatModel(model)}
              </span>
            )}
          </>
        )}
        <History className="w-3 h-3" style={{ color: 'var(--text-faint)' }} />
      </button>

      {isOpen && (
        <div
          className="absolute right-0 top-full mt-1 z-50 rounded-lg shadow-lg border overflow-hidden"
          style={{
            background: 'var(--bg-white, #fff)',
            borderColor: 'var(--border-light)',
            width: '340px',
            maxHeight: '400px',
          }}
        >
          {/* Header */}
          <div className="px-3 py-2 flex items-center justify-between" style={{ borderBottom: '1px solid var(--border-light)' }}>
            <span className="text-xs font-medium" style={{ color: 'var(--text-secondary)' }}>
              {field === 'ocr' ? 'OCR' : 'Translation'} History
              {total > 0 && <span className="ml-1" style={{ color: 'var(--text-muted)' }}>({total})</span>}
            </span>
            <button onClick={() => setIsOpen(false)} className="p-1.5 -mr-1 rounded hover:bg-stone-100" aria-label="Close history">
              <X className="w-3.5 h-3.5" style={{ color: 'var(--text-muted)' }} />
            </button>
          </div>

          {/* Current version */}
          <div className="px-3 py-2" style={{ background: 'rgba(139, 154, 125, 0.06)', borderBottom: '1px solid var(--border-light)' }}>
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-medium px-1.5 py-0.5 rounded" style={{ background: 'rgba(139, 154, 125, 0.2)', color: 'var(--accent-sage-dark)' }}>
                Current
              </span>
              {currentSource && <SourceBadge source={currentSource} />}
            </div>
          </div>

          {/* Revision list */}
          <div className="overflow-auto" style={{ maxHeight: '300px' }}>
            {loading ? (
              <div className="p-4 text-center text-xs" style={{ color: 'var(--text-muted)' }}>
                Loading...
              </div>
            ) : revisions.length === 0 ? (
              <div className="p-4 text-center text-xs" style={{ color: 'var(--text-muted)' }}>
                No previous versions
              </div>
            ) : (
              revisions.map((rev, idx) => (
                <div
                  key={rev.id}
                  className="border-b last:border-b-0"
                  style={{ borderColor: 'var(--border-light)' }}
                >
                  <button
                    onClick={() => setExpandedId(expandedId === rev.id ? null : rev.id)}
                    className="w-full px-3 py-2 flex items-center justify-between text-left hover:bg-stone-50 transition-colors"
                  >
                    <div className="flex items-center gap-2 min-w-0">
                      <span className="text-[10px] tabular-nums" style={{ color: 'var(--text-muted)' }}>
                        v{total - idx}
                      </span>
                      <SourceBadge source={rev.source} />
                      {rev.model && (
                        <span className="text-[10px] truncate" style={{ color: 'var(--text-faint)' }}>
                          {formatModel(rev.model)}
                        </span>
                      )}
                      {rev.edited_by && (
                        <span className="text-[10px] truncate" style={{ color: 'var(--text-faint)' }}>
                          {rev.edited_by}
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-1.5 flex-shrink-0">
                      <span className="text-[10px]" style={{ color: 'var(--text-faint)' }}>
                        {formatDate(rev.original_date || rev.created_at)}
                      </span>
                      <ChevronDown className={`w-3 h-3 transition-transform ${expandedId === rev.id ? 'rotate-180' : ''}`} style={{ color: 'var(--text-muted)' }} />
                    </div>
                  </button>

                  {expandedId === rev.id && (
                    <div className="px-3 pb-2">
                      {/* Preview */}
                      <div
                        className="text-[11px] leading-relaxed p-2 rounded mb-2 overflow-auto"
                        style={{
                          background: 'var(--bg-warm)',
                          color: 'var(--text-secondary)',
                          maxHeight: '120px',
                        }}
                      >
                        {truncate(rev.data, 500)}
                      </div>
                      <div className="flex items-center justify-between">
                        <span className="text-[10px]" style={{ color: 'var(--text-faint)' }}>
                          {rev.data.length.toLocaleString('en-US')} chars
                        </span>
                        {/* Reading the history is open to everyone — it is provenance,
                            and seeing how a page was corrected is part of the point.
                            Restoring rewrites the page, so it matches the editor gate
                            on the route behind it (#3511). Before this the button
                            rendered for every visitor and simply failed on click. */}
                        <AuthCheck role="inner_circle">
                          <button
                            onClick={(e) => { e.stopPropagation(); handleRestore(rev.id); }}
                            disabled={restoring === rev.id}
                            className="flex items-center gap-1 px-2.5 py-1.5 rounded text-[10px] font-medium transition-colors hover:bg-accent-gold/8"
                            style={{ color: 'var(--accent-rust)' }}
                          >
                            <RotateCcw className={`w-3 h-3 ${restoring === rev.id ? 'animate-spin' : ''}`} />
                            {restoring === rev.id ? 'Restoring...' : 'Restore'}
                          </button>
                        </AuthCheck>
                      </div>
                    </div>
                  )}
                </div>
              ))
            )}
          </div>
        </div>
      )}
    </div>
  );
}
