import type { Metadata } from 'next';
import DeepZoomViewer, { type DeepZoomItem } from './DeepZoomViewer';

export const metadata: Metadata = {
  title: 'Deep Zoom — prototype · Source Library',
  description:
    'A prototype tiled deep-zoom viewer for high-resolution artworks and engravings.',
  robots: { index: false, follow: false },
};

/**
 * Prototype only. Tile pyramids live in R2 under `deepzoom/<id>/` (generated by
 * the scratch script `_tmp-gen-deepzoom.mjs`). If this graduates to a real
 * feature, tiles should be produced by the image-extraction pipeline and the
 * manifest sourced from the DB rather than hard-coded here.
 */
const ITEMS: DeepZoomItem[] = [
  {
    id: 'khunrath-oratory',
    title: 'The Oratory & the Laboratory',
    book: 'Khunrath — Amphitheatre of Eternal Wisdom (1609)',
    width: 4132,
    height: 3565,
    tileSize: 256,
    overlap: 1,
    format: 'jpeg',
    tileBase: 'https://images.sourcelibrary.org/deepzoom/khunrath-oratory',
    source:
      'https://archive.org/download/BIUSante_pharma_res005272/page/n31/full/full/0/default.jpg',
    blurb:
      'Heinrich Khunrath’s famous engraving of the alchemist at prayer, flanked by his furnace and instruments. Zoom into the banners and the open books to read the Latin mottoes lettered into the plate.',
  },
  {
    id: 'blaeu-world-map',
    title: 'Nova Totius Terrarum Orbis — hand-coloured world map',
    book: 'Willem Blaeu — Toonneel des Aerdrycks (Amsterdam) · BPH',
    width: 7355,
    height: 5507,
    tileSize: 256,
    overlap: 1,
    format: 'jpeg',
    tileBase: 'https://images.sourcelibrary.org/deepzoom/blaeu-world-map',
    source:
      'https://images.uba.uva.nl/iiif/2/default!1!3!1!990011196650205131!otm-kzl-1804-a-2_004.jpg/full/max/0/default.jpg',
    blurb:
      'A 40-megapixel hand-coloured engraving from a Blaeu atlas. Zoom into the oceans to find the sailing ships and sea-creatures, then read the place-names threading across the continents and the allegorical borders — the four elements, the seasons, and the cities of the world.',
  },
  {
    id: 'kircher-china',
    title: 'Frontispiece',
    book: 'Kircher — China Illustrata (1667)',
    width: 3741,
    height: 5903,
    tileSize: 256,
    overlap: 1,
    format: 'jpeg',
    tileBase: 'https://images.sourcelibrary.org/deepzoom/kircher-china',
    source:
      'https://archive.org/download/athanasiikircher00kirc_0/page/n4/full/full/0/default.jpg',
    blurb:
      'The allegorical frontispiece to Athanasius Kircher’s study of China, with Jesuit missionaries and emblematic figures. The engraver’s hatching and the tiny inscriptions reward close inspection.',
  },
];

export default function DeepZoomPrototypePage() {
  return (
    <main className="mx-auto max-w-5xl px-4 py-10">
      <header className="mb-6">
        <p className="text-xs font-semibold uppercase tracking-wider text-amber-700">
          Prototype
        </p>
        <h1 className="mt-1 text-3xl font-semibold text-stone-900">Deep zoom</h1>
        <p className="mt-3 max-w-2xl leading-relaxed text-stone-600">
          A reader leaning in over an original engraving wants to read the tiny
          lettering, trace the hatching, follow a line of interlace. This viewer
          streams the image in tiles — only the detail you’re looking at is
          fetched — so even a 40-megapixel engraving stays sharp and fast. It’s the
          loupe-over-the-sheet experience our current magnifier can only
          approximate.
        </p>
      </header>

      <DeepZoomViewer items={ITEMS} />

      <section className="mt-8 max-w-2xl text-sm leading-relaxed text-stone-500">
        <h2 className="mb-1 font-medium text-stone-700">How it works</h2>
        <p>
          Each image is pre-cut into a pyramid of 256-px tiles (via{' '}
          <code className="rounded bg-stone-100 px-1">sharp</code>) from the
          full-resolution IIIF master and served from our image CDN. The viewer
          is OpenSeadragon. Today the three examples are pre-generated; in
          production the pipeline would tile artworks as it extracts them, and a
          “zoom” affordance would sit on every gallery image and book page.
        </p>
      </section>
    </main>
  );
}
