import { notFound } from 'next/navigation';
import { headers } from 'next/headers';
import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowLeft, ExternalLink, BookMarked } from 'lucide-react';
import { getTenantContextFromRequest } from '@/lib/tenant-context';
import alignmentData from '@/data/jung-bph-alignment-2026-05-22.json';

// Static virtual collection — built from a JSON artefact. Defer revalidation
// to a long interval since the underlying alignment is regenerated by hand
// (see scripts in #1933) and the file is committed.
export const revalidate = 86400;

export const metadata: Metadata = {
    title: "Jung Resonances — BPH",
    description:
        "Books from C.G. Jung's personal library at Küsnacht that are also held in the Bibliotheca Philosophica Hermetica. 151 bibliographic resonances between two of the most significant private libraries of Western esoteric thought.",
    robots: { index: true, follow: true },
};

interface JungWork {
    erara_id: string;
    title: string;
    author: string | null;
    year: number | null;
    source_url: string;
}

interface BphWork {
    ubn: string;
    title: string | null;
    author: string | null;
    year: number | null;
    place: string | null;
    publisher: string | null;
    printer: string | null;
    shelf_mark?: string | null;
    ustc_sn?: number | string | null;
    _normTitle?: string;
    _normAuthor?: string;
}

interface MatchEntry {
    bph: BphWork;
    score: number;
    titleShared: string[];
    authorShared: string[];
    yearScore: number;
}

interface AlignmentRecord {
    jung: JungWork;
    matches: MatchEntry[];
}

interface AlignmentData {
    generated_at: string;
    oai_set: string;
    jung_count: number;
    matched_count: number;
    not_in_bph_count: number;
    results: AlignmentRecord[];
}

const DATA = alignmentData as unknown as AlignmentData;

interface FlatMatch {
    jung: JungWork;
    bph: BphWork;
    score: number;
    yearScore: number;
}

function buildMatchedList(data: AlignmentData): FlatMatch[] {
    const matched = data.results.filter(r => r.matches && r.matches.length > 0);
    const flat: FlatMatch[] = matched.map(r => {
        const best = r.matches[0];
        return {
            jung: r.jung,
            bph: best.bph,
            score: best.score,
            yearScore: best.yearScore,
        };
    });
    flat.sort((a, b) => {
        const ay = a.bph.year ?? 9999;
        const by = b.bph.year ?? 9999;
        if (ay !== by) return ay - by;
        return b.score - a.score;
    });
    return flat;
}

function ustcLabel(bph: BphWork): string | null {
    if (bph.ustc_sn) return 'USTC-confirmed';
    return null;
}

function imprintLine(bph: BphWork): string {
    const parts: string[] = [];
    if (bph.place) parts.push(bph.place);
    if (bph.printer) parts.push(bph.printer.replace(/\|/g, ' / '));
    else if (bph.publisher) parts.push(bph.publisher.replace(/\|/g, ' / '));
    return parts.join(' · ');
}

export default async function JungResonancesPage() {
    // BPH-tenant-gated. The data references BPH UBNs and the in-page links
    // (`/catalog/{ubn}`) only resolve under the BPH subdomain rewrite, so
    // rendering this page off-BPH would produce broken links and violate the
    // tenant-lockdown invariant. After Phase Final the route is global, but the
    // gate stays.
    const { slug: tenantSlug } = getTenantContextFromRequest(await headers());
    if (tenantSlug !== 'bph') notFound();

    const matched = buildMatchedList(DATA);
    const ustcCount = matched.filter(m => !!m.bph.ustc_sn).length;
    const fuzzyCount = matched.length - ustcCount;

    return (
        <div className="min-h-screen bg-cream">
            {/* Header / breadcrumb */}
            <div className="bg-white border-b border-border-light">
                <div className="max-w-5xl mx-auto px-6 py-4">
                    <Link
                        href="/"
                        className="inline-flex items-center gap-2 text-sm text-secondary hover:text-accent-rust transition-colors"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        BPH home
                    </Link>
                </div>
            </div>

            {/* Hero */}
            <div className="bg-gradient-to-br from-stone-900 via-stone-800 to-stone-900 text-white">
                <div className="max-w-5xl mx-auto px-6 py-12 sm:py-16">
                    <p className="text-xs uppercase tracking-[0.3em] text-accent-gold font-semibold mb-4">
                        Virtual Collection
                    </p>
                    <h1 className="text-4xl sm:text-5xl lg:text-6xl font-display font-semibold leading-[1.1] mb-6 max-w-3xl">
                        Jung Resonances
                    </h1>
                    <p className="text-lg text-stone-300 max-w-3xl leading-relaxed mb-8">
                        Of the {DATA.jung_count} books in Jung&apos;s personal library at the
                        Stiftung der Werke von C.G. Jung in Küsnacht (digitised at
                        e-rara.ch), {DATA.matched_count} are also held in the Bibliotheca
                        Philosophica Hermetica. This page surfaces those bibliographic
                        resonances — works Jung read in his own copy that the BPH also
                        preserves, often in a different edition. Both libraries can be
                        opened side by side.
                    </p>

                    {/* Stats strip */}
                    <div className="flex flex-wrap gap-8 sm:gap-12 text-sm">
                        <div>
                            <div className="text-3xl font-bold text-accent-gold tabular-nums">
                                {DATA.matched_count}
                            </div>
                            <div className="text-xs text-stone-400 uppercase tracking-wider mt-1">
                                Shared works
                            </div>
                        </div>
                        <div>
                            <div className="text-3xl font-bold text-accent-gold tabular-nums">
                                {ustcCount}
                            </div>
                            <div className="text-xs text-stone-400 uppercase tracking-wider mt-1">
                                USTC-anchored
                            </div>
                        </div>
                        <div>
                            <div className="text-3xl font-bold text-accent-gold tabular-nums">
                                {fuzzyCount}
                            </div>
                            <div className="text-xs text-stone-400 uppercase tracking-wider mt-1">
                                Fuzzy matches
                            </div>
                        </div>
                        <div>
                            <div className="text-3xl font-bold text-accent-gold tabular-nums">
                                {Math.round((DATA.matched_count / Math.max(DATA.jung_count, 1)) * 100)}%
                            </div>
                            <div className="text-xs text-stone-400 uppercase tracking-wider mt-1">
                                Of Jung&apos;s library
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Card list */}
            <main className="max-w-5xl mx-auto px-6 py-10">
                <ul className="space-y-4">
                    {matched.map((m, i) => (
                        <ResonanceCard key={`${m.bph.ubn}-${m.jung.erara_id}-${i}`} match={m} />
                    ))}
                </ul>

                {/* Methodology drawer */}
                <details className="mt-12 group border border-border-light rounded-lg bg-white open:shadow-sm">
                    <summary className="cursor-pointer px-5 py-4 text-sm font-medium text-secondary hover:text-primary transition-colors list-none flex items-center justify-between">
                        <span>Method &amp; sources</span>
                        <span className="text-xs text-muted group-open:rotate-180 transition-transform">▾</span>
                    </summary>
                    <div className="px-5 pb-5 text-sm text-secondary leading-relaxed space-y-3 border-t border-border-light pt-4">
                        <p>
                            Jung&apos;s personal library (OAI set <code className="text-xs bg-warm px-1.5 py-0.5 rounded">cgj</code>) was
                            harvested from <a
                                href="https://www.e-rara.ch/zuz/nav/classification/22942117"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-accent-rust hover:underline inline-flex items-center gap-1"
                            >
                                e-rara.ch
                                <ExternalLink className="w-3 h-3" />
                            </a> ({DATA.jung_count} titles digitised by the Zentralbibliothek
                            Zürich on behalf of the Stiftung der Werke von C.G. Jung).
                        </p>
                        <p>
                            Each Jung title was matched against the BPH catalogue using
                            shared significant words in title and author surname, plus
                            year proximity (≤10 years). The highest-scoring BPH candidate
                            per Jung title is shown above. {ustcCount} of the {matched.length} matches
                            carry a USTC SN on the BPH side — those are identity-grade
                            (USTC covers pre-1651 imprints, so coverage is concentrated
                            in the earlier years).
                        </p>
                        <p>
                            Source data and the full alignment table (including the {DATA.not_in_bph_count} Jung
                            titles with no BPH match) are available in the{' '}
                            <a
                                href="https://github.com/Embassy-of-the-Free-Mind/sourcelibrary-v2/blob/main/.claude/docs/jung-bph-alignment-2026-05-22.md"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-accent-rust hover:underline inline-flex items-center gap-1"
                            >
                                project repository
                                <ExternalLink className="w-3 h-3" />
                            </a>.
                            Alignment generated {new Date(DATA.generated_at).toISOString().slice(0, 10)}.
                        </p>
                    </div>
                </details>
            </main>
        </div>
    );
}

function ResonanceCard({ match }: { match: FlatMatch }) {
    const { jung, bph, score } = match;
    const bphTitle = bph.title || '(untitled)';
    const bphAuthor = bph.author || jung.author || '';
    const imprint = imprintLine(bph);
    const ustc = ustcLabel(bph);
    const isIdentityMatch = score >= 12;
    const yearsDiffer = jung.year && bph.year && jung.year !== bph.year;

    return (
        <li className="bg-white rounded-lg border border-border-light hover:border-accent-rust/30 hover:shadow-sm transition-all">
            <div className="p-5 sm:p-6 grid sm:grid-cols-[1fr_auto] gap-4">
                <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-2 mb-2">
                        {bph.year != null && (
                            <span className="text-xs font-mono text-muted tabular-nums">
                                {bph.year}
                            </span>
                        )}
                        {ustc && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-[10px] uppercase tracking-wider rounded-full bg-accent-rust/10 text-accent-rust border border-accent-rust/30">
                                {ustc}
                            </span>
                        )}
                        {!ustc && isIdentityMatch && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-[10px] uppercase tracking-wider rounded-full bg-stone-100 text-stone-600 border border-stone-300">
                                Strong match
                            </span>
                        )}
                    </div>

                    <h2 className="text-lg sm:text-xl text-primary font-display leading-snug mb-1">
                        <Link
                            href={`/catalog/${bph.ubn}`}
                            className="hover:text-accent-rust transition-colors"
                        >
                            {bphTitle}
                        </Link>
                    </h2>
                    {bphAuthor && (
                        <p className="text-sm text-secondary mb-1">
                            {bphAuthor}
                        </p>
                    )}
                    {imprint && (
                        <p className="text-xs text-muted">
                            {imprint}
                            {bph.shelf_mark && (
                                <>
                                    <span className="mx-2">·</span>
                                    <span className="font-mono">shelf {bph.shelf_mark}</span>
                                </>
                            )}
                        </p>
                    )}

                    <div className="mt-4 pt-3 border-t border-border-light/60">
                        <a
                            href={jung.source_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-start gap-1.5 text-sm text-secondary hover:text-accent-rust transition-colors group/jung"
                        >
                            <BookMarked className="w-4 h-4 mt-0.5 shrink-0 text-muted group-hover/jung:text-accent-rust" />
                            <span>
                                Jung also owned this — see his copy at Küsnacht
                                {yearsDiffer && (
                                    <span className="text-muted ml-1">
                                        (Jung&apos;s copy: {jung.year})
                                    </span>
                                )}
                                <ExternalLink className="w-3 h-3 ml-1 inline-block align-baseline opacity-60 group-hover/jung:opacity-100" />
                            </span>
                        </a>
                    </div>
                </div>

                <div className="hidden sm:flex flex-col items-end justify-start text-xs text-muted">
                    <Link
                        href={`/catalog/${bph.ubn}`}
                        className="font-mono text-muted hover:text-accent-rust transition-colors whitespace-nowrap"
                    >
                        UBN {bph.ubn}
                    </Link>
                </div>
            </div>
        </li>
    );
}
