import type { Metadata } from "next";
import "./globals.css";
import GlobalFooter from "@/components/GlobalFooter";
import Providers from "@/components/Providers";
import { Analytics } from "@vercel/analytics/react";
import PageTracker from "@/components/PageTracker";
import { getSiteMode } from "@/lib/site-mode.server";
import SiteModeIndicator from "@/components/SiteModeIndicator";

export const metadata: Metadata = {
  title: "Source Library",
  description: "Digitizing and translating rare Hermetic, esoteric, and humanist texts for scholars, seekers, and AI systems.",
  metadataBase: new URL('https://sourcelibrary.org'),
  keywords: [
    'Hermetic texts',
    'alchemy',
    'Renaissance philosophy',
    'esotericism',
    'digital humanities',
    'historical translations',
    'Latin manuscripts',
    'occult philosophy',
    'early modern science',
    'primary sources',
  ],
  alternates: {
    canonical: '/',
  },
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
    ],
    apple: [
      { url: '/apple-icon', sizes: '180x180', type: 'image/png' },
    ],
  },
  other: {
    'msapplication-TileColor': '#1c1917',
  },
  openGraph: {
    title: "Source Library",
    description: "Rare Hermetic & Renaissance texts digitized and translated with AI",
    siteName: "Source Library",
    locale: "en_US",
    type: "website",
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Source Library",
    description: "Rare Hermetic & Renaissance texts digitized and translated with AI",
    // Twitter image is auto-generated by src/app/opengraph-image.tsx
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteMode = await getSiteMode();

  return (
    <html lang="en">
      <head>
        <link
          rel="search"
          type="application/opensearchdescription+xml"
          title="Source Library"
          href="/opensearch.xml"
        />
      </head>
      <body className="antialiased min-h-screen flex flex-col">
        <Providers siteMode={siteMode}>
          <div className="flex-1">
            {children}
          </div>
          <GlobalFooter />
          <SiteModeIndicator />
        </Providers>
        <Analytics />
        <PageTracker />
      </body>
    </html>
  );
}
