import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service - Source Library',
  description: 'Terms of service for Source Library.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ background: 'var(--bg-cream)' }}>
      <header className="border-b" style={{ background: 'var(--bg-white)', borderColor: 'var(--border-light)' }}>
        <div className="max-w-3xl mx-auto px-6 py-4">
          <Link href="/" className="text-sm hover:opacity-70 transition-opacity" style={{ color: 'var(--text-muted)' }}>
            &larr; Back to Source Library
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-medium mb-8" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>
          Terms of Service
        </h1>
        <div className="prose-content space-y-6 text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
          <p><strong>Effective date:</strong> February 22, 2026</p>

          <p>
            Source Library (&ldquo;the Service&rdquo;) is operated by the Ancient Wisdom Trust
            in partnership with the Embassy of the Free Mind, Amsterdam.
            By using the Service, you agree to these terms.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>1. The Service</h2>
          <p>
            Source Library provides digitized historical texts with AI-generated translations,
            OCR transcriptions, and extracted illustrations. Content is provided for scholarly,
            educational, and personal use.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>2. Accounts</h2>
          <p>
            Some content requires a free account. You must provide a valid email address.
            You are responsible for keeping your account credentials secure.
            We may suspend accounts that violate these terms.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>3. Content and Copyright</h2>
          <p>
            The original texts on Source Library are in the public domain. AI-generated translations,
            transcriptions, summaries, and metadata are provided under the{' '}
            <a href="https://creativecommons.org/licenses/by/4.0/" className="underline" target="_blank" rel="noopener noreferrer">
              Creative Commons Attribution 4.0 International License (CC BY 4.0)
            </a>.
            You may copy, redistribute, and build upon this material for any purpose, provided
            you give appropriate credit to Source Library.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>4. AI-Generated Content</h2>
          <p>
            Translations and summaries are generated by AI and may contain errors.
            They are intended as scholarly aids, not authoritative translations.
            Users should verify content against original sources for academic citation.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>5. Acceptable Use</h2>
          <p>
            You agree not to: scrape the Service at scale without permission;
            misrepresent AI-generated translations as human translations;
            use the Service for any unlawful purpose;
            or attempt to interfere with the Service&rsquo;s operation.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>6. Disclaimer</h2>
          <p>
            The Service is provided &ldquo;as is&rdquo; without warranty of any kind.
            We do not guarantee the accuracy of translations or the availability of the Service.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>7. Changes</h2>
          <p>
            We may update these terms from time to time. Continued use of the Service
            after changes constitutes acceptance.
          </p>

          <h2 className="text-lg font-medium mt-8 mb-3" style={{ fontFamily: 'Cormorant Garamond, Georgia, serif', color: 'var(--text-primary)' }}>8. Contact</h2>
          <p>
            Questions about these terms? Contact us at{' '}
            <a href="mailto:derek@ancientwisdomtrust.org" className="underline">derek@ancientwisdomtrust.org</a>.
          </p>
        </div>
      </main>
    </div>
  );
}
