'use client';

interface DataSource {
  label: string;
  description: string;
  count: number;
  coverage?: number;
}

interface DataSourcesProps {
  sources: Record<string, DataSource>;
}

export default function DataSources({ sources }: DataSourcesProps) {
  const entries = Object.entries(sources);

  return (
    <div className="space-y-4">
      <h2 className="font-serif text-2xl" style={{ color: 'var(--text-primary)' }}>
        Data Sources
      </h2>
      <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>
        All visualizations on this page are derived from the following data pipeline. Entity data is extracted by AI from
        book indexes, then enriched with structured data from Wikidata.
      </p>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {entries.map(([key, source]) => (
          <div
            key={key}
            className="rounded-lg p-4"
            style={{ background: 'var(--bg-white, #fff)', border: '1px solid var(--border-light)' }}
          >
            <div className="flex items-baseline justify-between mb-1">
              <span className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>
                {source.label}
              </span>
              <span className="text-sm font-mono" style={{ color: 'var(--text-secondary)' }}>
                {source.count.toLocaleString()}
              </span>
            </div>
            <p className="text-xs leading-relaxed" style={{ color: 'var(--text-muted)' }}>
              {source.description}
            </p>
            {source.coverage !== undefined && (
              <div className="mt-2">
                <div className="flex items-center gap-2">
                  <div
                    className="flex-1 h-1.5 rounded-full overflow-hidden"
                    style={{ background: 'var(--border-light)' }}
                  >
                    <div
                      className="h-full rounded-full transition-all"
                      style={{
                        width: `${Math.min(source.coverage, 100)}%`,
                        background: 'var(--accent-sage)',
                      }}
                    />
                  </div>
                  <span className="text-xs font-medium" style={{ color: 'var(--accent-sage-dark)' }}>
                    {source.coverage}%
                  </span>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      <div
        className="rounded-lg p-4 text-xs leading-relaxed"
        style={{ background: 'var(--bg-warm)', color: 'var(--text-muted)' }}
      >
        <strong style={{ color: 'var(--text-secondary)' }}>Pipeline:</strong>{' '}
        Book indexes are generated by Gemini AI from OCR&apos;d page text. Entities (people, places, concepts) are
        extracted and deduplicated across all books. Wikidata alignment matches entities by Wikipedia URL or exact name
        search, pulling in structured biographical dates (P569/P570), geographic coordinates (P625), and QIDs. Only
        high-confidence matches are used — lower-confidence suggestions are excluded from counts.
      </div>
    </div>
  );
}
