-- Volunteer ratings for the human-in-the-loop review site (issue #2107).
--
-- Each row is a single judgment by a single volunteer on a single item.
-- Multiple volunteers rate the same item; consensus is computed downstream.
-- `queue` is the rating task ('hallucination', 'page_type', etc.).
-- `item_id` is task-specific (e.g. <book_id>:<page_number> for the
-- hallucination queue).
-- `detail` is free-form jsonb (e.g. the corrected page_type, the phrase
-- the volunteer flagged as hallucinated, etc.).
-- `volunteer_id` is a per-browser uuid generated by the client; nullable
-- for the rare server-issued case. No PII.

CREATE TABLE IF NOT EXISTS volunteer_ratings (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  queue         text NOT NULL,
  item_id       text NOT NULL,
  rating        text NOT NULL,
  detail        jsonb,
  volunteer_id  uuid,
  volunteer_label text,
  user_agent    text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS volunteer_ratings_queue_item_idx
  ON volunteer_ratings (queue, item_id);
CREATE INDEX IF NOT EXISTS volunteer_ratings_volunteer_idx
  ON volunteer_ratings (volunteer_id, created_at DESC);

-- RLS: anonymous inserts allowed via the anon role for this table only.
-- Reads are restricted to service-role until the admin UI lands.
ALTER TABLE volunteer_ratings ENABLE ROW LEVEL SECURITY;

CREATE POLICY volunteer_ratings_insert_anon
  ON volunteer_ratings
  FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY volunteer_ratings_service_all
  ON volunteer_ratings
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
