import { PromptReference } from "./prompt";

export interface Page {
  id: string;
  tenant_id: string;
  book_id: string;
  page_number: number;
  photo: string;
  thumbnail?: string;
  compressed_photo?: string;
  ocr?: OcrData;
  translation?: TranslationData;
  summary?: SummaryData;
  modernized?: ModernizedData;  // Modernized text for reading dashboard
  created_at?: Date;
  updated_at?: Date;

  // Analytics
  read_count?: number;
  edit_count?: number;

  // Detected illustrations/images on this page
  detected_images?: DetectedImage[];

  // Split/crop workflow
  photo_original?: string;      // Original S3 URL before cropping
  cropped_photo?: string;       // Local path to cropped image
  archived_photo?: string;      // Vercel Blob URL for archived IA images
  crop?: CropData;              // Crop coordinates used
  split_from?: string;          // ID of parent page if this was split from another
  split_detection?: {           // Pixel analysis result
    isTwoPageSpread: boolean;
    confidence: 'high' | 'medium' | 'low';
    splitPosition: number;      // 0-1000 scale
    splitPositionPercent: number;
    hasTextAtSplit: boolean;
    textWarning?: string;
    metrics: {
      aspectRatio: number;
      gutterScore: number;
      maxDarkRunAtSplit: number;
      transitionsAtSplit: number;
      windowAvgDarkRun: number;
      windowAvgTransitions: number;
    };
    detected_at?: Date;
  };
}

// Processing metadata for reproducibility and cost tracking
export interface ProcessingMetadata {
  input_tokens?: number;
  output_tokens?: number;
  cost_usd?: number;
  processing_ms?: number;
  prompt_url?: string;   // GitHub URL to exact prompt version used (deprecated)
  prompt?: PromptReference;  // Reference to versioned prompt
}

// Source tracking for edits
export type ContentSource = 'ai' | 'manual';

export interface OcrData extends ProcessingMetadata {
  language: string;
  model: string;
  data: string;
  image_urls?: string[];
  updated_at?: Date;
  prompt_name?: string;
  // Source tracking
  source?: ContentSource;     // 'ai' = generated by AI, 'manual' = edited by user
  edited_by?: string;         // User name who made the edit
  edited_at?: Date;           // When the manual edit was made
}

export interface TranslationData extends ProcessingMetadata {
  language: string;
  model: string;
  data: string;
  updated_at?: Date;
  prompt_name?: string;
  // Source tracking
  source?: ContentSource;     // 'ai' = generated by AI, 'manual' = edited by user
  edited_by?: string;         // User name who made the edit
  edited_at?: Date;           // When the manual edit was made
}

export interface SummaryData extends ProcessingMetadata {
  data: string;
  model: string;
  updated_at?: Date;
  prompt_name?: string;
  // Source tracking
  source?: ContentSource;
  edited_by?: string;
  edited_at?: Date;
}

// ============================================
// PAGE SNAPSHOTS (backup before re-processing)
// ============================================

/**
 * Snapshot of page content before AI re-processing.
 * Created automatically when re-processing a page that has manual edits.
 * Allows restoring manually-edited content if AI output is worse.
 */
export interface PageSnapshot {
  id: string;
  _id?: string;
  page_id: string;
  book_id: string;

  // What triggered the snapshot
  snapshot_type: 'pre_ocr' | 'pre_translate' | 'pre_summary' | 'manual_backup';

  // The content that was saved
  ocr_data?: string;
  translation_data?: string;
  summary_data?: string;

  // Who had edited this content
  ocr_edited_by?: string;
  translation_edited_by?: string;

  // When the snapshot was created
  created_at: Date;

  // What job triggered this (if any)
  triggered_by_job_id?: string;

  // Whether this snapshot has been restored
  restored_at?: Date;
  restored_by?: string;
}

// Modernized text for reading dashboard
export interface ModernizedData {
  data: string;
  model: string;
  updated_at?: Date;
  prompt_name?: string;
  source_translation_hash?: string;  // Hash of translation.data to detect changes
}

// Crop coordinates for split pages (0-1000 scale)
export interface CropData {
  xStart: number;
  xEnd: number;
  yStart?: number;
  yEnd?: number;
}

// Detected illustration/image on a page (from OCR or vision model)
export type DetectionStatus = 'pending' | 'approved' | 'rejected';

// Structured metadata for indexing/search
export interface ImageMetadata {
  subjects?: string[];          // Topics: "alchemy", "transformation", "nature"
  figures?: string[];           // People/beings: "old man", "serpent", "Mercury"
  symbols?: string[];           // Symbols: "ouroboros", "philosophical egg", "athanor"
  style?: string;               // Art style: "Northern European Renaissance"
  technique?: string;           // Production: "woodcut", "engraving with crosshatching"
  condition?: string;           // Physical state: "good", "fair", "poor"
}

export interface DetectedImage {
  id?: string;                  // Unique ID for this detection
  description: string;          // What the image depicts (brief)
  type?: 'woodcut' | 'diagram' | 'chart' | 'illustration' | 'symbol' | 'table' | 'map' | 'decorative' | 'emblem' | 'engraving' | 'portrait' | 'frontispiece' | 'musical_score' | 'unknown';
  // Bounding box (0-1 normalized coordinates, for future extraction)
  bbox?: {
    x: number;      // Left edge (0-1)
    y: number;      // Top edge (0-1)
    width: number;  // Width (0-1)
    height: number; // Height (0-1)
  };
  extracted_url?: string;       // URL to extracted/cropped image (future)
  detected_at?: Date;
  detection_source: 'ocr_tag' | 'vision_model' | 'manual';
  model?: 'gemini' | 'mistral' | 'grounding-dino';
  confidence?: number;
  status?: DetectionStatus;     // Review status: pending (default), approved, rejected
  reviewed_at?: Date;
  reviewed_by?: string;
  // Gallery curation
  gallery_quality?: number;     // 0-1 score: how gallery-worthy is this image?
  gallery_rationale?: string;   // Why it scored high/low (visual appeal, historical significance, etc.)
  featured?: boolean;           // Manually marked as gallery-worthy
  // Rich metadata for indexing and display
  metadata?: ImageMetadata;     // Structured tags for search/filtering
  museum_description?: string;  // 2-3 sentence museum-style label
}