/**
 * Eval ledgers that cannot conflict (#5436).
 *
 * Two PRs appending to the same tail of EXPERIMENTS.md were a textual conflict every
 * time (6 of 11 needs-rebase PRs on 2026-10-01). The treatment is one file per entry,
 * concatenated into EXPERIMENTS.md on main by build-experiments.mjs, plus a detector
 * that finds the NEXT file to acquire that shape. These tests pin the two mechanisms:
 * the builder's ordering and validation, and the detector's classification.
 */
import { mkdtempSync, writeFileSync, rmSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { describe, it, expect, afterAll } from 'vitest';
import { buildExperiments } from '../../scripts/eval/build-experiments.mjs';
import { appendStats, classify, unionPatterns, REGENERATED_ON_MAIN } from '../../scripts/audit/append-only-ledgers.mjs';

const dirs: string[] = [];
function tmp(files: Record<string, string>) {
  const d = mkdtempSync(join(tmpdir(), 'experiments-'));
  for (const [n, t] of Object.entries(files)) writeFileSync(join(d, n), t);
  dirs.push(d);
  return d;
}
afterAll(() => { for (const d of dirs) rmSync(d, { recursive: true, force: true }); });

describe('buildExperiments', () => {
  it('renders header + banner, series first, dated entries newest first, notes last', () => {
    const d = tmp({
      'README.md': '# Experiment log\n\nRules here.\n',
      '_series-monthly.md': '## Monthly series\n\n| a |\n',
      '2026-09-30-older.md': '## 2026-09-30 · Older question (#1)\n\n- **Result.** x\n',
      '2026-10-01-newer.md': '## 2026-10-01 · Newer question (#2)\n\n- **Result.** y\n',
      '_note-older-runs.md': '## Older runs\n\nnot back-filled\n',
    });
    const { text, problems, counts } = buildExperiments(d);
    expect(problems).toEqual([]);
    expect(counts).toEqual({ series: 1, dated: 2, notes: 1 });
    expect(text.startsWith('# Experiment log\n\n<!-- GENERATED by scripts/eval/build-experiments.mjs')).toBe(true);
    const order = ['## Monthly series', '## 2026-10-01', '## 2026-09-30', '## Older runs'].map((h) => text.indexOf(h));
    expect(order.every((i) => i >= 0)).toBe(true);
    expect([...order].sort((a, b) => a - b)).toEqual(order);
  });

  it('reports a heading whose date disagrees with the filename, a stray file, and a conflict marker', () => {
    const d = tmp({
      'README.md': '# Log\n',
      '2026-10-01-wrong-date.md': '## 2026-09-30 · mislabelled\n',
      'notes.md': '## not a dated entry\n',
      '2026-10-02-marker.md': '## 2026-10-02 · ok heading\n<<<<<<< HEAD\n',
    });
    const { problems } = buildExperiments(d);
    expect(problems.some((p) => p.includes('2026-10-01-wrong-date.md') && p.includes('must match'))).toBe(true);
    expect(problems.some((p) => p.startsWith('notes.md'))).toBe(true);
    expect(problems.some((p) => p.includes('2026-10-02-marker.md') && p.includes('conflict'))).toBe(true);
  });

  it('names a missing README as a problem instead of throwing', () => {
    const d = tmp({ '2026-10-01-x.md': '## 2026-10-01 · x\n' });
    expect(buildExperiments(d).problems[0]).toMatch(/README/);
  });
});

describe('append-only-ledgers detector', () => {
  const sha = (n: number) => n.toString(16).padStart(40, '0');
  // 10 commits: ledger.md appended in 9 and edited in 1; code.ts edited in all; GEN.md rewritten in all.
  const log = Array.from({ length: 10 }, (_, i) =>
    `${sha(i + 1)}\n${i === 0 ? '3\t2' : '4\t0'}\tdocs/ledger.md\n5\t3\tsrc/code.ts\n12\t11\tdocs/GEN.md\n`).join('\n');

  it('appendStats counts commits and insertion-only commits per path', () => {
    const s = appendStats(log);
    expect(s.get('docs/ledger.md')).toEqual({ commits: 10, appendOnly: 9 });
    expect(s.get('src/code.ts')).toEqual({ commits: 10, appendOnly: 0 });
  });

  it('classify flags an untreated append-only ledger and a per-PR-regenerated file, and skips code', () => {
    const findings = classify(appendStats(log), {
      tracked: new Set(['docs/ledger.md', 'src/code.ts', 'docs/GEN.md']),
      isUnion: () => false,
      isRegenerated: () => false,
      headOf: (p: string) => (p === 'docs/GEN.md' ? '<!-- GENERATED by x -->' : 'prose'),
    });
    expect(findings.map((f) => [f.path, f.kind, f.treated])).toEqual([
      ['docs/ledger.md', 'append-only', null],
      ['docs/GEN.md', 'generated-per-pr', null],
    ]);
  });

  it('classify marks treated files ok and respects the thresholds', () => {
    const base = { tracked: new Set(['docs/ledger.md', 'docs/GEN.md']), headOf: () => 'prose' };
    const treated = classify(appendStats(log), { ...base, isUnion: (p: string) => p === 'docs/ledger.md', isRegenerated: () => false });
    expect(treated.find((f) => f.path === 'docs/ledger.md')?.treated).toBe('union');
    const strict = classify(appendStats(log), { ...base, isUnion: () => false, isRegenerated: () => false, ratio: 0.95 });
    expect(strict.find((f) => f.path === 'docs/ledger.md')).toBeUndefined();
    const few = classify(appendStats(log), { ...base, isUnion: () => false, isRegenerated: () => false, minCommits: 11 });
    expect(few).toEqual([]);
  });

  it('unionPatterns turns .gitattributes globs into path matchers', () => {
    const res = unionPatterns('# c\nscripts/eval/DECISIONS.md merge=union\nscripts/eval/experiments/_series-*.md   merge=union\nfoo.md text\n');
    expect(res).toHaveLength(2);
    expect(res.some((re) => re.test('scripts/eval/DECISIONS.md'))).toBe(true);
    expect(res.some((re) => re.test('scripts/eval/experiments/_series-monthly.md'))).toBe(true);
    expect(res.some((re) => re.test('scripts/eval/experiments/sub/_series-x.md'))).toBe(false);
    expect(res.some((re) => re.test('foo.md'))).toBe(false);
  });

  it('the two generated ledgers are the ones main regenerates', () => {
    expect(Object.keys(REGENERATED_ON_MAIN).sort()).toEqual(['scripts/eval/EXPERIMENTS.md', 'scripts/eval/INDEX.md']);
  });
});
