/**
 * Related holdings for cited works we do NOT hold in a readable copy — the cited
 * edition may be in copyright (Chadwick, des Places…) or no PD edition exists at all.
 * Keyed "author|work". At most 3 per work; each carries a one-phrase relation label
 * chosen by the classifier from a fixed set (never free text). Generated by
 * scripts/enrichment/shwep-cited-works.mjs --related (gemini-3.1-flash-lite). Do not edit by hand.
 */
export interface ShwepRelatedHolding {
  id: string;
  slug: string | null;
  title: string;
  author: string;
  year: number | null;
  relation: string;
}
export const SHWEP_RELATED_WORKS: Record<string, ShwepRelatedHolding[]> = {
  "Aelius Aristides|Hieroi Logoi": [
    {
      "id": "69e8b2352ff2a8dc09e76de6",
      "slug": "meditationes-aurelius",
      "title": "Τὰ εἰς ἑαυτόν (Meditationes)",
      "author": "Marcus Aurelius",
      "year": 1652,
      "relation": "the same tradition"
    },
    {
      "id": "6a089c1a2b703903f58e859f",
      "slug": "marcus-cornelius-fronto-correspondence-with-marcus-aurelius-haines",
      "title": "Marcus Cornelius Fronto: Correspondence with Marcus Aurelius, Lucius Verus, and Others, Vo",
      "author": "Fronto; trans. C.R. Haines",
      "year": 1919,
      "relation": "the same tradition"
    }
  ],
  "Damascius|Life of Isidore": [
    {
      "id": "69a9768ee12635ded71c4e2f",
      "slug": "quaestiones-de-primis-principiis-kopp",
      "title": "Problems Concerning First Principles",
      "author": "Damascius (ed. Joseph Kopp)",
      "year": 1826,
      "relation": "by the same author"
    },
    {
      "id": "69a99cef6c7545e2236e177c",
      "slug": "problemes-et-solutions-touchant-les-premiers-principes-vol-1-damascius",
      "title": "Problems and Solutions Concerning First Principles, Volume 1",
      "author": "Damascius",
      "year": 1898,
      "relation": "by the same author"
    },
    {
      "id": "69a99d006c7545e2236e1a79",
      "slug": "problemes-et-solutions-touchant-les-premiers-principes-vol-3-damascius",
      "title": "Problems and Solutions Concerning First Principles, Volume 3",
      "author": "Damascius",
      "year": 1898,
      "relation": "by the same author"
    }
  ],
  "Anonymous|Allogenes": [
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "the same tradition"
    }
  ],
  "Numenius of Apamea|Fragments": [
    {
      "id": "6a3f02bb97e91e1768f68204",
      "slug": "fragmenta-philosophorum-graecorum-mullach",
      "title": "Fragments of Greek Philosophers",
      "author": "Mullach, F. W. A. (Friedrich Wilhelm August), b. 1807",
      "year": 1881,
      "relation": "contains excerpts"
    },
    {
      "id": "69a5e5e385fa13e734e41894",
      "slug": "procli-opera-grec-1839-proclus",
      "title": "Commentary on Plato's Timaeus",
      "author": "Proclus",
      "year": 1360,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Sefer ha-Razim": [
    {
      "id": "69b3e67c304c1c6b3950b7c3",
      "slug": "collection-of-kabbalah-and-hekhalot-texts-ms-michael-9-various",
      "title": "Book of Creation and Jewish Mystical Texts",
      "author": "Various",
      "year": 1350,
      "relation": "the same tradition"
    },
    {
      "id": "69c1bae58522835be845b540",
      "slug": "incantations-and-amulets-anonymous",
      "title": "Incantations and amulets (Gaster Hebrew MS 177)",
      "author": "Anonymous",
      "year": 1650,
      "relation": "the same tradition"
    },
    {
      "id": "69c1bb8e8522835be84603f3",
      "slug": "magical-incantations-medial-prescriptions-and-amulets-anonymous",
      "title": "Magical incantations, medial prescriptions and amulets (Gaster Hebrew MS 1485)",
      "author": "Anonymous",
      "year": 1650,
      "relation": "the same tradition"
    }
  ],
  "Damascius|In Parmenidem": [
    {
      "id": "69a9768ee12635ded71c4e2f",
      "slug": "quaestiones-de-primis-principiis-kopp",
      "title": "Problems Concerning First Principles",
      "author": "Damascius (ed. Joseph Kopp)",
      "year": 1826,
      "relation": "by the same author"
    },
    {
      "id": "69a99cef6c7545e2236e177c",
      "slug": "problemes-et-solutions-touchant-les-premiers-principes-vol-1-damascius",
      "title": "Problems and Solutions Concerning First Principles, Volume 1",
      "author": "Damascius",
      "year": 1898,
      "relation": "by the same author"
    },
    {
      "id": "69a99d006c7545e2236e1a79",
      "slug": "problemes-et-solutions-touchant-les-premiers-principes-vol-3-damascius",
      "title": "Problems and Solutions Concerning First Principles, Volume 3",
      "author": "Damascius",
      "year": 1898,
      "relation": "by the same author"
    }
  ],
  "Olympiodorus the Younger|Commentary on the Alcibiades": [
    {
      "id": "69b52cceb3537347e51e316d",
      "slug": "olympiodorus-scholia-on-aristotle-s-meteorology-neoplatonic-aristotle",
      "title": "Olympiodorus, Scholia on Aristotle's Meteorology (Neoplatonic)",
      "author": "Olympiodorus; Aristotle",
      "year": 1450,
      "relation": "by the same author"
    },
    {
      "id": "6a0856a515c643eb1af596e8",
      "slug": "olympiodorou-philosophou-alexandreos-eis-ta-meteora-tou-aris",
      "title": "Olympiodōrou philosophou Alexandreōs eis ta Meteōra tou Aristotelous ypomnemata. Ioannou G",
      "author": "Olympiodorus : Alexandrinus filosofo (filosofo)",
      "year": 1551,
      "relation": "by the same author"
    },
    {
      "id": "6990592aaaa7f10ed4cfaa42",
      "slug": "procli-diadochi-in-platonis-timaeum-commentaria-vol-ii-diehl",
      "title": "Commentary on Plato's Timaeus, Volume II",
      "author": "Proclus (ed. Ernst Diehl)",
      "year": 1904,
      "relation": "the same tradition"
    }
  ],
  "Kartir|Kartir Inscriptions": [
    {
      "id": "699243d2bc722ec0ee80a13d",
      "slug": "the-dinkard-acts-of-the-religion-of-zoroaster-sanjana",
      "title": "The Dinkard: Acts of the Religion of Zoroaster",
      "author": "Peshotun Dustoor Behramjee Sanjana",
      "year": 1874,
      "relation": "the same tradition"
    }
  ],
  "Damascius|In Phaedonem": [
    {
      "id": "69a9768ee12635ded71c4e2f",
      "slug": "quaestiones-de-primis-principiis-kopp",
      "title": "Problems Concerning First Principles",
      "author": "Damascius (ed. Joseph Kopp)",
      "year": 1826,
      "relation": "by the same author"
    },
    {
      "id": "69a99cef6c7545e2236e177c",
      "slug": "problemes-et-solutions-touchant-les-premiers-principes-vol-1-damascius",
      "title": "Problems and Solutions Concerning First Principles, Volume 1",
      "author": "Damascius",
      "year": 1898,
      "relation": "by the same author"
    },
    {
      "id": "6a3f021a661123baf6fe9c51",
      "slug": "das-leben-des-philosophen-isidoros-von-damaskios-aus-damaskios",
      "title": "The Life of the Philosopher Isidoros by Damaskios of Damascus",
      "author": "Damaskios",
      "year": 1911,
      "relation": "by the same author"
    }
  ],
  "Heraclitus|Fragments": [
    {
      "id": "6983d45e3dac6d74d7e4b195",
      "slug": "de-heraclito-ephesio-haec-apud-facultatem-litterarum-dauriac",
      "title": "On Heraclitus of Ephesus",
      "author": "Lionel Alexandre Dauriac",
      "year": 1887,
      "relation": "commentary on it"
    },
    {
      "id": "69ae66b14b74f168e0c14dce",
      "slug": "the-first-philosophers-of-greece-remaining-fragments-of-the-ed",
      "title": "The First Philosophers of Greece: Remaining Fragments of the Pre-Sokratic Philosophers",
      "author": "Arthur Fairbanks (ed.)",
      "year": 1898,
      "relation": "contains excerpts"
    },
    {
      "id": "6a3f02bb97e91e1768f68204",
      "slug": "fragmenta-philosophorum-graecorum-mullach",
      "title": "Fragments of Greek Philosophers",
      "author": "Mullach, F. W. A. (Friedrich Wilhelm August), b. 1807",
      "year": 1881,
      "relation": "contains excerpts"
    }
  ],
  "Zosimus of Panopolis|Matters Alchemical": [
    {
      "id": "69ae9bbbad53d7103d61fcfb",
      "slug": "zosimi-panopolitani-de-zymotechnia-panopolis",
      "title": "On the Art of Fermentation",
      "author": "Zosimos of Panopolis",
      "year": 1814,
      "relation": "by the same author"
    },
    {
      "id": "69b4c048978ca9526eda33a3",
      "slug": "democritus-sacred-art-of-alchemy-with-synesius-commentary-synesius",
      "title": "Democritus, Sacred Art of Alchemy (with Synesius commentary)",
      "author": "Pseudo-Democritus; Synesius",
      "year": 1550,
      "relation": "the same tradition"
    },
    {
      "id": "69b4c04d978ca9526eda33f7",
      "slug": "sacred-art-of-the-philosophers-greek-alchemical-anthology-various",
      "title": "Sacred Art of the Philosophers (Greek alchemical anthology)",
      "author": "Various",
      "year": 1495,
      "relation": "the same tradition"
    }
  ],
  "Zosimus of Panopolis|On the Letter Omega": [
    {
      "id": "6994383a6879ff0184cb803a",
      "slug": "collection-des-anciens-alchimistes-grecs-vols-2-3-berthelot",
      "title": "Collection of the Ancient Greek Alchemists, Vols. 2-3",
      "author": "Marcellin Berthelot",
      "year": 1888,
      "relation": "contains excerpts"
    },
    {
      "id": "69ac7ed620878c5c9ba51ad0",
      "slug": "collection-des-anciens-alchimistes-grecs-seconde-livraison-ruelle",
      "title": "Collection of Ancient Greek Alchemists, Part 2",
      "author": "Marcellin Berthelot & Charles-Émile Ruelle",
      "year": 1888,
      "relation": "contains excerpts"
    },
    {
      "id": "69b4c04d978ca9526eda33f7",
      "slug": "sacred-art-of-the-philosophers-greek-alchemical-anthology-various",
      "title": "Sacred Art of the Philosophers (Greek alchemical anthology)",
      "author": "Various",
      "year": 1495,
      "relation": "the same tradition"
    }
  ],
  "Porphyry|Ad Gaurum": [
    {
      "id": "6955770557e3b773024f2d40",
      "slug": "opuscula-tria-incl-vita-pythagorae-ed",
      "title": "Three Short Works (including Life of Pythagoras)",
      "author": "Porphyry; August Nauck (ed.)",
      "year": 1886,
      "relation": "by the same author"
    },
    {
      "id": "6a3f02af97e91e1768f67e3a",
      "slug": "vie-de-porphyre-le-philosophe-neo-platonicien-avec-les-bidez",
      "title": "Life of Porphyry the Neoplatonist Philosopher",
      "author": "Bidez, Joseph, 1867-1945",
      "year": 1913,
      "relation": "the same tradition"
    }
  ],
  "Al-Kulayni|Al-Kāfī": [
    {
      "id": "69d5ac2ed0bd3547a565582f",
      "slug": "the-catalogue-al-nadim",
      "title": "كتاب الفهرست (The Catalogue)",
      "author": "Ibn al-Nadim",
      "year": 1872,
      "relation": "the same tradition"
    }
  ],
  "Al-Suyuti|Itqān fi ‘ulūm al-Qur'ān": [
    {
      "id": "6a06cde4c749b698e5b2cc6a",
      "slug": "al-wishah-fi-fawa-id-al-nikah-treatise-on-the-benefits-of",
      "title": "الوشاح في فوائد النكاح al-Wishāḥ fī fawāʾid al-nikāḥ — Treatise on the Benefits of Marriag",
      "author": "Jalāl al-Dīn al-Suyūṭī (السيوطي)",
      "year": 1505,
      "relation": "by the same author"
    }
  ],
  "Al-Sulami|Ṭabaqāt al-Ṣūfiyya": [
    {
      "id": "69b63e7f2a1dde00d5a9e314",
      "slug": "al-risala-al-qushayriyya-treatise-on-sufism-al-qushayri",
      "title": "Al-Risala al-Qushayriyya (Treatise on Sufism)",
      "author": "Al-Qushayri",
      "year": 1870,
      "relation": "the same tradition"
    },
    {
      "id": "69b63e87535439aaa48911a3",
      "slug": "kitab-al-luma-book-of-flashes-ed",
      "title": "Kitab al-Luma (Book of Flashes)",
      "author": "Abu Nasr al-Sarraj; R.A. Nicholson (ed.)",
      "year": 1914,
      "relation": "the same tradition"
    }
  ],
  "Anatolius of Alexandria|On the Decad": [
    {
      "id": "69557433f63a75710917330c",
      "slug": "introductionis-arithmeticae-libri-ii-gerasa",
      "title": "Introduction to Arithmetic",
      "author": "Nicomachus of Gerasa",
      "year": 1866,
      "relation": "the same tradition"
    },
    {
      "id": "69a956bf65ddd05bbcd3cf12",
      "slug": "theologumena-arithmeticae-ast",
      "title": "The Theology of Arithmetic",
      "author": "Iamblichus / Nicomachus (ed. Friedrich Ast)",
      "year": 1817,
      "relation": "the same tradition"
    },
    {
      "id": "69d148841c2a66dc094b2304",
      "slug": "theologumena-arithmeticae-ast-2",
      "title": "Theologumena Arithmeticae",
      "author": "Iamblichus; ed. Friedrich Ast",
      "year": 1817,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Anonymous Prolegomena to Platonic Philosophy": [
    {
      "id": "69a5e5d91d73f9668388ef2b",
      "slug": "plotini-enneades-13th-c-copy-a-plotinus",
      "title": "The Enneads",
      "author": "Plotinus",
      "year": 1200,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f02cd97e91e1768f685fb",
      "slug": "initia-philosophi-ac-theologi-ex-platonicis-fontibus-ducta-412-485",
      "title": "Beginnings of Philosophy and Theology from Platonic Sources",
      "author": "Proclus (412-485)",
      "year": 1820,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Apocryphon of John": [
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f02d297e91e1768f68766",
      "slug": "koptisch-gnostische-schriften-hrsg-im-auftrage-der-schmidt",
      "title": "Coptic-Gnostic Writings",
      "author": "Schmidt, Carl, 1868-1938",
      "year": 1905,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Books of Jeu": [
    {
      "id": "69a5ea03d507939f0352c8df",
      "slug": "le-jeu-des-echecs-moralises-vignay",
      "title": "The Game of Chess Moralized",
      "author": "Jacques de Cessoles (trans. Jean de Vignay)",
      "year": 1350,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Cambridge Gloss on the Apocalypse": [
    {
      "id": "6a0c53f399c52ea845a06406",
      "slug": "medieval-commentary-on-the-apocalypse-of-john-anonymous",
      "title": "Medieval Commentary on the Apocalypse of John",
      "author": "Anonymous",
      "year": 1400,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Corpus inscriptionum et monumentorum religionis Mithriacæ": [
    {
      "id": "6992545159cdabeb78f1dc13",
      "slug": "religion-und-kultus-der-romer-wissowa",
      "title": "Religion and Cult of the Romans",
      "author": "Georg Wissowa",
      "year": 1902,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Epidauran Miracle Inscriptions": [
    {
      "id": "6a3f024697e91e1768f66b92",
      "slug": "inscriptiones-graecae-volume-4-fraenkel",
      "title": "Greek Inscriptions Volume 4",
      "author": "Maximilianus Fraenkel",
      "year": 1902,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|First Apocalypse of James": [
    {
      "id": "69924671bc722ec0ee80c069",
      "slug": "the-apocryphal-new-testament-james",
      "title": "The Apocryphal New Testament",
      "author": "M. R. James",
      "year": 1924,
      "relation": "contains excerpts"
    },
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f02d297e91e1768f68766",
      "slug": "koptisch-gnostische-schriften-hrsg-im-auftrage-der-schmidt",
      "title": "Coptic-Gnostic Writings",
      "author": "Schmidt, Carl, 1868-1938",
      "year": 1905,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Gospel of Truth": [
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f02d297e91e1768f68766",
      "slug": "koptisch-gnostische-schriften-hrsg-im-auftrage-der-schmidt",
      "title": "Coptic-Gnostic Writings",
      "author": "Schmidt, Carl, 1868-1938",
      "year": 1905,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Gospel of Judas": [
    {
      "id": "69924671bc722ec0ee80c069",
      "slug": "the-apocryphal-new-testament-james",
      "title": "The Apocryphal New Testament",
      "author": "M. R. James",
      "year": 1924,
      "relation": "contains excerpts"
    },
    {
      "id": "6993574e83378b7aed7cf419",
      "slug": "pistis-sophia-a-gnostic-gospel-trans",
      "title": "Pistis Sophia: A Gnostic Gospel",
      "author": "G.R.S. Mead (trans.)",
      "year": 1921,
      "relation": "the same tradition"
    },
    {
      "id": "69c884a06c6f3cc53c8599e5",
      "slug": "pistis-sophia-a-gnostic-gospel-with-extracts-from-the-books",
      "title": "Pistis sophia. A gnostic gospel (with extracts from the books of the saviour appended)",
      "author": "Unknown",
      "year": 1896,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Greek Musical Writings": [
    {
      "id": "6955742bf63a757109172ca1",
      "slug": "antiquae-musicae-auctores-septem-graece-et-latine-quintilianus",
      "title": "Seven Authors of Ancient Music",
      "author": "Marcus Meibom (ed.); Aristoxenus; Euclid; Nicomachus; Alypius; Gaudentius; Bacchius; Aristides Quintilianus",
      "year": 1652,
      "relation": "the same tradition"
    },
    {
      "id": "69938a8fd5a98fd66f42d175",
      "slug": "bodleian-library-ms-barocci-41-nicomachus",
      "title": "Musical Treatises of Euclid, Aristoxenus, Porphyry, and Nicomachus",
      "author": "Euclid; Aristoxenus; Porphyry; Nicomachus",
      "year": 1450,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Letter of Peter to Philip": [
    {
      "id": "69d5ae22d0bd3547a5656c4d",
      "slug": "acts-of-the-apostles-manchester-ethiopic-ms-6-anonymous",
      "title": "ገድለ ሐዋርያት (Acts of the Apostles — Manchester Ethiopic MS 6)",
      "author": "Anonymous",
      "year": 1400,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Liber vaccae": [
    {
      "id": "6991c58c3074a1745a411b3b",
      "slug": "alchemical-miscellany-latin-ms-65-various",
      "title": "Alchemical miscellany (Latin MS 65)",
      "author": "Paul of Tarento; Friar Elias; Various",
      "year": 1415,
      "relation": "contains excerpts"
    }
  ],
  "Anonymous|Magical Book of Mary and the Angels": [
    {
      "id": "6952872fab34727b1f04d5b2",
      "slug": "enchiridion-leonis-papae-pope-leo-s-enchiridion-iii",
      "title": "The Enchiridion of Pope Leo",
      "author": "Pseudo-Leo III",
      "year": 1633,
      "relation": "the same tradition"
    },
    {
      "id": "69905e292fd6a039938a15c6",
      "slug": "liber-incantationum-exorcismorum-et-fascinationum-munich-anonymous",
      "title": "Munich Necromantic Handbook",
      "author": "Anonymous",
      "year": 1450,
      "relation": "the same tradition"
    },
    {
      "id": "69c899356c6f3cc53c85cd2d",
      "slug": "romanus-buchlein-anonymous",
      "title": "Romanus-Büchlein",
      "author": "anonymous",
      "year": 1850,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Memphis Decree": [
    {
      "id": "69e013b193b116d24238b35c",
      "slug": "hieroglyphic-texts-from-egyptian-stelae-part-iv",
      "title": "Hieroglyphic Texts from Egyptian Stelae, Part IV",
      "author": "British Museum",
      "year": 1913,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Narratio de aedificatione Sanctae Sophiae": [
    {
      "id": "6a3f025497e91e1768f66fb0",
      "slug": "scriptores-originum-constantinopolitanarum-preger",
      "title": "Writings on the Origins of Constantinople",
      "author": "Preger, Theodor, d. 1911",
      "year": 1901,
      "relation": "commentary on it"
    }
  ],
  "Anonymous|On the World and the Soul": [
    {
      "id": "69dbc7ed1040d1d5e2095820",
      "slug": "de-anima-comm-johannes-mechlinia-add-gerardus-de-harderwyck-aristoteles",
      "title": "On the Soul",
      "author": "Aristoteles",
      "year": 1491,
      "relation": "the same tradition"
    },
    {
      "id": "69dbcafc1040d1d5e20b03ce",
      "slug": "in-librum-aristotelis-de-anima-offredus",
      "title": "Exposition on Aristotle's On the Soul",
      "author": "Offredus, Apollinaris",
      "year": 1496,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Parastaseis Syntomoi Chronikai": [
    {
      "id": "6a3f025497e91e1768f66fb0",
      "slug": "scriptores-originum-constantinopolitanarum-preger",
      "title": "Writings on the Origins of Constantinople",
      "author": "Preger, Theodor, d. 1911",
      "year": 1901,
      "relation": "commentary on it"
    }
  ],
  "Anonymous|Prayer of Thanksgiving": [
    {
      "id": "69bfccc18ab50eb88e8c6317",
      "slug": "bodleian-library-ms-cromwell-11-anonymous",
      "title": "Gospel Lectionary",
      "author": "Anonymous",
      "year": 1440,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Passio and Miracles of St. Mercurius": [
    {
      "id": "69d5ae22d0bd3547a5656c4d",
      "slug": "acts-of-the-apostles-manchester-ethiopic-ms-6-anonymous",
      "title": "ገድለ ሐዋርያት (Acts of the Apostles — Manchester Ethiopic MS 6)",
      "author": "Anonymous",
      "year": 1400,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Scholia on Plato's Alcibiades I": [
    {
      "id": "69a5e5d91d73f9668388ef2b",
      "slug": "plotini-enneades-13th-c-copy-a-plotinus",
      "title": "The Enneads",
      "author": "Plotinus",
      "year": 1200,
      "relation": "the same tradition"
    },
    {
      "id": "69a5e5e385fa13e734e41894",
      "slug": "procli-opera-grec-1839-proclus",
      "title": "Commentary on Plato's Timaeus",
      "author": "Proclus",
      "year": 1360,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Secundus the Silent Philosopher": [
    {
      "id": "69dbc9b71040d1d5e20a597e",
      "slug": "vitae-et-sententiae-philosophorum-tr-ambrosius-traversarius-diogenes-laertius-2",
      "title": "Vitae et sententiae philosophorum (Tr: Ambrosius Traversarius. Ed: Benedictus Brognolus)",
      "author": "Diogenes Laertius",
      "year": 1493,
      "relation": "the same tradition"
    },
    {
      "id": "69dbc9b91040d1d5e20a5a64",
      "slug": "vitae-et-sententiae-philosophorum-tr-ambrosius-traversarius-diogenes-laertius-3",
      "title": "Vitae et sententiae philosophorum. Tr: Ambrosius Traversarius. Ed: Benedictus Brognolus",
      "author": "Diogenes Laertius",
      "year": 1495,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Sophia of Jesus Christ": [
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f02d297e91e1768f68766",
      "slug": "koptisch-gnostische-schriften-hrsg-im-auftrage-der-schmidt",
      "title": "Coptic-Gnostic Writings",
      "author": "Schmidt, Carl, 1868-1938",
      "year": 1905,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Symphonia Alchemica": [
    {
      "id": "699067f8249ce014347d530c",
      "slug": "pal-lat-1328-various-pseudo",
      "title": "Anthology of Hermetic and Alchemical Treatises",
      "author": "Various (Pseudo-Hermes, Pseudo-Arnald)",
      "year": 1450,
      "relation": "the same tradition"
    },
    {
      "id": "6a1009d0f71729295096c07a",
      "slug": "deutsches-theatrum-chemicum-auf-welchem-der-beruhmtesten-s-n",
      "title": "Deutsches theatrum chemicum, auf welchem der berühmtesten Philosophen und Alchymisten Schr",
      "author": "Roth-Scholtz, Friedrich (1687-1736)",
      "year": 1728,
      "relation": "contains excerpts"
    }
  ],
  "Anonymous|Syriac Legend of Alexander’s Gate": [
    {
      "id": "69c1bd308522835be8468096",
      "slug": "romance-of-alexander-anonymous",
      "title": "Romance of Alexander (Armenian MS 3)",
      "author": "Anonymous",
      "year": 1544,
      "relation": "the same tradition"
    },
    {
      "id": "69d66bfd4da4f8dce52f24d4",
      "slug": "pseudo-callisthenes-romance-of-alexander-armenian-version-pseudo-callisthenes",
      "title": "Pseudo-Callisthenes — Romance of Alexander (Armenian version, 1646)",
      "author": "Pseudo-Callisthenes",
      "year": 1646,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Tosefta Hagigah": [
    {
      "id": "69920befebe5b0fa6be5d569",
      "slug": "mishnah-kaufmann-manuscript-complete-anonymous",
      "title": "Mishnah: Kaufmann Manuscript (Complete)",
      "author": "Anonymous",
      "year": 1929,
      "relation": "the same tradition"
    },
    {
      "id": "69c1bc3a8522835be8461fe6",
      "slug": "excerpts-from-the-hebrew-bible-mishnah-and-gemara-anonymous",
      "title": "Excerpts from the Hebrew Bible, Mishnah and Gemara (Gaster Hebrew MS 2041)",
      "author": "Anonymous",
      "year": 1850,
      "relation": "contains excerpts"
    },
    {
      "id": "69d5ac5f4dc55b8478ddd6b5",
      "slug": "babylonian-talmud-vilna-romm-edition-1884-various-romm-press",
      "title": "תלמוד בבלי (Babylonian Talmud — Vilna Romm Edition, 1884)",
      "author": "Various (Romm Press, Vilna)",
      "year": 1884,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Treatise on the Resurrection": [
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f02d297e91e1768f68766",
      "slug": "koptisch-gnostische-schriften-hrsg-im-auftrage-der-schmidt",
      "title": "Coptic-Gnostic Writings",
      "author": "Schmidt, Carl, 1868-1938",
      "year": 1905,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Tripartite Tractate": [
    {
      "id": "69c884a06c6f3cc53c8599e5",
      "slug": "pistis-sophia-a-gnostic-gospel-with-extracts-from-the-books",
      "title": "Pistis sophia. A gnostic gospel (with extracts from the books of the saviour appended)",
      "author": "Unknown",
      "year": 1896,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f035697e91e1768f6a0b5",
      "slug": "epiphanius-epiphanius",
      "title": "Ancoratus and Panarion",
      "author": "Epiphanius, Saint, Bishop of Constantia in Cyprus, ca. 310-403",
      "year": 1915,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Tübingen Theosophy": [
    {
      "id": "69c822ed6c6f3cc53c84ae7d",
      "slug": "versuch-einer-auflosung-der-177-fragen-aus-jakob-bohm-oetinger",
      "title": "Versuch einer Auflösung der 177. Fragen aus Jakob Böhm",
      "author": "[Oetinger, Friedrich Christoph]",
      "year": 1777,
      "relation": "commentary on it"
    },
    {
      "id": "69c88b9f6c6f3cc53c85a997",
      "slug": "tafel-der-wiedergeburt-boehme",
      "title": "Tafel der Wiedergeburt",
      "author": "Boehme, Jacob",
      "year": 1728,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Yerushalmi Hagigah": [
    {
      "id": "69d5ac5f4dc55b8478ddd6b5",
      "slug": "babylonian-talmud-vilna-romm-edition-1884-various-romm-press",
      "title": "תלמוד בבלי (Babylonian Talmud — Vilna Romm Edition, 1884)",
      "author": "Various (Romm Press, Vilna)",
      "year": 1884,
      "relation": "the same tradition"
    },
    {
      "id": "69d5ac824dc55b8478dddb9a",
      "slug": "well-of-jacob-aggadic-talmud-vilna-1883-jacob-ibn-habib",
      "title": "עין יעקב (Well of Jacob — Aggadic Talmud, Vilna 1883)",
      "author": "Jacob ibn Habib (Romm Press, Vilna)",
      "year": 1883,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Umm al-Kitab": [
    {
      "id": "6a09eaa83ca4edcd1ef022ea",
      "slug": "hazreti-fazl-i-yezdanin-ottoman-turkish-translation-of-the-hurufi",
      "title": "Ḥażreti Fażl-i Yezdāniñ — Ottoman Turkish translation of the Jāvidān-nāma",
      "author": "Ḥurūfī, Faḍl Allāh (Astarābādī)",
      "year": 1800,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Zostrianos": [
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "contains excerpts"
    },
    {
      "id": "6a3f02d297e91e1768f68766",
      "slug": "koptisch-gnostische-schriften-hrsg-im-auftrage-der-schmidt",
      "title": "Coptic-Gnostic Writings",
      "author": "Schmidt, Carl, 1868-1938",
      "year": 1905,
      "relation": "contains excerpts"
    },
    {
      "id": "6a3f035697e91e1768f6a0b5",
      "slug": "epiphanius-epiphanius",
      "title": "Ancoratus and Panarion",
      "author": "Epiphanius, Saint, Bishop of Constantia in Cyprus, ca. 310-403",
      "year": 1915,
      "relation": "the same tradition"
    }
  ],
  "Apollonius of Tyana|Book of Wisdom and of the Science of Talismans": [
    {
      "id": "69520ee0ab34727b1f044285",
      "slug": "picatrix-the-goal-of-the-wise-al-majriti",
      "title": "The Goal of the Wise",
      "author": "Pseudo-Maslama al-Majriti",
      "year": 1500,
      "relation": "the same tradition"
    },
    {
      "id": "695361cd9c494f9f9f042f19",
      "slug": "ghayat-al-hakim-arabic-ms-al-majriti",
      "title": "The Goal of the Wise (Ghayat al-Hakim)",
      "author": "Maslama al-Majriti",
      "year": 960,
      "relation": "the same tradition"
    },
    {
      "id": "69b3e596c94a4ff7cce22d4f",
      "slug": "collection-of-magical-and-other-treatises-ascribed-to-trismegistus",
      "title": "Collected Treatises on Magic and Nature",
      "author": "Hermes Trismegistus",
      "year": 1325,
      "relation": "the same tradition"
    }
  ],
  "Ashoka|Inscriptions of Ashoka": [
    {
      "id": "69d5adf3d0bd3547a5656821",
      "slug": "great-chronicle-of-ceylon-geiger",
      "title": "මහාවංශය (Great Chronicle of Ceylon)",
      "author": "Mahanama (trans. Wilhelm Geiger)",
      "year": 1912,
      "relation": "the same tradition"
    },
    {
      "id": "69e13b340dae29249d20c297",
      "slug": "kauilyas-arthastra",
      "title": "Kauṭilya's Arthaśāstra",
      "author": "Kauṭilya; R. Shamasastry, ed.",
      "year": 1909,
      "relation": "the same tradition"
    },
    {
      "id": "69e961c22beefe2f6f72cce6",
      "slug": "ancient-india-as-described-by-megasthenes-and-arrian-mccrindle",
      "title": "Ancient India as Described by Megasthenes and Arrian",
      "author": "Megasthenes (ed. McCrindle)",
      "year": 1877,
      "relation": "the same tradition"
    }
  ],
  "George Pachymeres|Paraphrasis in opera S. Dionysii Areopagitae": [
    {
      "id": "69a5e5e385fa13e734e41894",
      "slug": "procli-opera-grec-1839-proclus",
      "title": "Commentary on Plato's Timaeus",
      "author": "Proclus",
      "year": 1360,
      "relation": "the same tradition"
    }
  ],
  "Evagrius of Pontus|Epistula fidei": [
    {
      "id": "69a5f366d4c2e3cf8ecb8a85",
      "slug": "theological-and-philosophical-anthology-various",
      "title": "Theological and Philosophical Anthology",
      "author": "Various",
      "year": 800,
      "relation": "contains excerpts"
    },
    {
      "id": "69a5f3b61cf742c3604134ce",
      "slug": "syriac-theological-anthology-various",
      "title": "Syriac Theological Anthology",
      "author": "Various",
      "year": 1200,
      "relation": "contains excerpts"
    }
  ],
  "Elias|In Categorias": [
    {
      "id": "69b3e5ca304c1c6b3950a3a9",
      "slug": "commentary-on-porphyry-isagoge-philosophical-texts-ammonius",
      "title": "Commentary on Porphyry's Introduction and Philosophical Texts",
      "author": "Ammonius",
      "year": 1295,
      "relation": "the same tradition"
    },
    {
      "id": "69b43d4dee0300187dbd1906",
      "slug": "porphyry-isagoge-neoplatonic-commentaries-proclus-ammonius-ammonius",
      "title": "Porphyry Isagoge & Neoplatonic Commentaries (Proclus, Ammonius)",
      "author": "Porphyry; Proclus; Ammonius",
      "year": 1350,
      "relation": "the same tradition"
    },
    {
      "id": "69b4c09f86a5921d5bc44c9f",
      "slug": "porphyry-ammonius-commentary-on-aristotle-s-categories-ammonius",
      "title": "Porphyry & Ammonius, Commentary on Aristotle's Categories",
      "author": "Porphyry; Ammonius",
      "year": 1250,
      "relation": "the same tradition"
    }
  ],
  "Pseudo-Augustine|De spiritu et anima": [
    {
      "id": "69dbc7ed1040d1d5e2095820",
      "slug": "de-anima-comm-johannes-mechlinia-add-gerardus-de-harderwyck-aristoteles",
      "title": "On the Soul",
      "author": "Aristoteles",
      "year": 1491,
      "relation": "the same tradition"
    },
    {
      "id": "6a0c53f799c52ea845a064e0",
      "slug": "augustine-de-trinitate-books-1-8-hippo",
      "title": "Augustine: De Trinitate (Books 1–8)",
      "author": "Augustine of Hippo",
      "year": 1180,
      "relation": "the same tradition"
    }
  ],
  "Evagrius of Pontus|Kephalaia Gnostika": [
    {
      "id": "69a5f366d4c2e3cf8ecb8a85",
      "slug": "theological-and-philosophical-anthology-various",
      "title": "Theological and Philosophical Anthology",
      "author": "Various",
      "year": 800,
      "relation": "contains excerpts"
    },
    {
      "id": "69b3e5c6304c1c6b3950a1b2",
      "slug": "de-mystica-theologia-de-caelesti-hierarchia-areopagite",
      "title": "Mystical Theology and The Celestial Hierarchy",
      "author": "Pseudo-Dionysius the Areopagite",
      "year": 1505,
      "relation": "the same tradition"
    }
  ],
  "Hierocles of Alexandria|De Providentia": [
    {
      "id": "69ac7ede20878c5c9ba51d76",
      "slug": "the-commentary-of-hierocles-upon-the-golden-verses-of-alexandria",
      "title": "The Commentary of Hierocles upon the Golden Verses of Pythagoras",
      "author": "Hierocles of Alexandria",
      "year": 1756,
      "relation": "by the same author"
    }
  ],
  "Ḥusayn Vāʿiz Kāshifī|Rawḍat al-Shuhadāʾ": [
    {
      "id": "69e53460d48480a386965df0",
      "slug": "anwar-i-suhaili-lights-of-canopus",
      "title": "Anwar-i Suhaili (Lights of Canopus)",
      "author": "Husain Va'iz Kashifi (trans. Wollaston)",
      "year": 1877,
      "relation": "by the same author"
    },
    {
      "id": "69e72994a409200ea79f093f",
      "slug": "anvar-i-suhayli-kashifi",
      "title": "انوار سهیلی (Anvār-i Suhaylī)",
      "author": "Husain Vāʻiz Kāshifī",
      "year": 1894,
      "relation": "by the same author"
    }
  ],
  "Ibn Bahlul|Kitab ad-Dala'il": [
    {
      "id": "69d5ac2ed0bd3547a565582f",
      "slug": "the-catalogue-al-nadim",
      "title": "كتاب الفهرست (The Catalogue)",
      "author": "Ibn al-Nadim",
      "year": 1872,
      "relation": "the same tradition"
    }
  ],
  "Ibn Kathīr|Al-Bidāyah wa l-Nihāyah": [
    {
      "id": "69e961342beefe2f6f72a891",
      "slug": "muruj-al-dhahab-meadows-of-gold-al-masudi",
      "title": "مروج الذهب (Murūj al-Dhahab / Meadows of Gold)",
      "author": "Al-Masudi",
      "year": 1841,
      "relation": "the same tradition"
    }
  ],
  "Ibn Qūlawayh|Kāmil al-Ziyārāt": [
    {
      "id": "69d5ac2ed0bd3547a565582f",
      "slug": "the-catalogue-al-nadim",
      "title": "كتاب الفهرست (The Catalogue)",
      "author": "Ibn al-Nadim",
      "year": 1872,
      "relation": "the same tradition"
    }
  ],
  "Iamblichus|In Platonis dialogos commentariorum fragmenta": [
    {
      "id": "69d13d751c2a66dc094b168d",
      "slug": "de-mysteriis-liber-parthey-critical-edition-parthey",
      "title": "On the Mysteries",
      "author": "Iamblichus; ed. Gustav Parthey",
      "year": 1857,
      "relation": "by the same author"
    },
    {
      "id": "69d143e91c2a66dc094b1ba5",
      "slug": "de-vita-pythagorica-liber-pars-2-kiessling-kiessling",
      "title": "On the Pythagorean Life",
      "author": "Iamblichus; ed. J.G. Kiessling",
      "year": 1816,
      "relation": "by the same author"
    },
    {
      "id": "69d147041c2a66dc094b2174",
      "slug": "in-nicomachi-arithmeticam-introductionem-pistelli-pistelli",
      "title": "On Nicomachus's Introduction to Arithmetic",
      "author": "Iamblichus; ed. Ermenegildo Pistelli",
      "year": 1894,
      "relation": "by the same author"
    }
  ],
  "Jābir ibn Ḥayyān|Kitāb Usṭuqus al-uss al-thānī": [
    {
      "id": "6953619d9c494f9f9f042608",
      "slug": "majmu-nafis-fi-al-kimiya-jabir-ibn-hayyan-hayyan",
      "title": "A Precious Collection on Alchemy",
      "author": "Jabir ibn Hayyan",
      "year": 800,
      "relation": "by the same author"
    },
    {
      "id": "69d5ac2ed0bd3547a565582f",
      "slug": "the-catalogue-al-nadim",
      "title": "كتاب الفهرست (The Catalogue)",
      "author": "Ibn al-Nadim",
      "year": 1872,
      "relation": "contains excerpts"
    }
  ],
  "John Chrysostom|Adversus Oppugnatores Vitae Monasticae": [
    {
      "id": "69b3004ca1a4246ddb45c267",
      "slug": "lucubrationes-1527-chrysostom",
      "title": "Lucubrations",
      "author": "John Chrysostom",
      "year": 1527,
      "relation": "by the same author"
    },
    {
      "id": "6a0854c249638a50931c0a1b",
      "slug": "sancti-ioannis-chrysostomi-de-virginitate-liber-a-iulio-pogi",
      "title": "Sancti Ioannis Chrysostomi De virginitate liber, a Iulio Pogiano conuersus.",
      "author": "Manuzio, Paolo",
      "year": 1562,
      "relation": "by the same author"
    }
  ],
  "John Chrysostom|Adversus Judaeos": [
    {
      "id": "69c807206c6f3cc53c84578e",
      "slug": "greek-in-sactos-maccabaeos-et-in-eorum-matrem-homilia-chrysostomus",
      "title": "[Greek] In sactos Maccabaeos, et in eorum matrem, homilia",
      "author": "Johannes Chrysostomus",
      "year": 1620,
      "relation": "by the same author"
    },
    {
      "id": "69c8072e6c6f3cc53c8457b9",
      "slug": "greek-omilia-chrysostomus",
      "title": "[Greek: Omilia]",
      "author": "Johannes Chrysostomus",
      "year": 1619,
      "relation": "by the same author"
    },
    {
      "id": "69dbca731040d1d5e20ac5d0",
      "slug": "de-fide-catholica-contra-judaeos-isidorus-hispalensis",
      "title": "De fide catholica contra Judaeos",
      "author": "Isidorus Hispalensis",
      "year": 1485,
      "relation": "the same tradition"
    }
  ],
  "Leo VI the Wise|Book of the Eparch": [
    {
      "id": "69a5e621e751f06e74b89925",
      "slug": "oracula-leonis-sapientis-barocci-170-emperor",
      "title": "The Oracles of Leo the Wise",
      "author": "Leo VI (Emperor)",
      "year": 1577,
      "relation": "by the same author"
    },
    {
      "id": "69b62f6d1c1c21a3737f5c9f",
      "slug": "justiniani-imperatoris-edicta-constitutiones-aliquot-civilis",
      "title": "Justiniani imperatoris Edicta. Constitutiones aliquot Justiniani, Justini, et Tiberii ex l",
      "author": "Justinian I",
      "year": 1580,
      "relation": "the same tradition"
    }
  ],
  "Justinian I|Codex Justinianus": [
    {
      "id": "69a97a0cdaf647306a73737d",
      "slug": "theodosiani-libri-xvi-vol-1-ii",
      "title": "Theodosian Code, Volume 1",
      "author": "Theodosius II",
      "year": 1905,
      "relation": "the same tradition"
    },
    {
      "id": "69b631401c1c21a373805f27",
      "slug": "iustiniani-institutiones-mit-der-glossa-ordinaria-des-accursius",
      "title": "[Iustiniani Institutiones]",
      "author": "Accursius, Franciscus",
      "year": 1476,
      "relation": "commentary on it"
    },
    {
      "id": "69b65b5918b87551bfd0c1fb",
      "slug": "dn-sacratissimi-principis-justiniani-pp-a-juris-enucleati-pace",
      "title": "DN. sacratissimi principis Justiniani PP. A. Juris enucleati ex omni vetere jure collecti ",
      "author": "Pace, Giulio",
      "year": 1580,
      "relation": "commentary on it"
    }
  ],
  "Leontius of Byzantium|Complete Works": [
    {
      "id": "69942f83b2f6748db4ac128c",
      "slug": "maximus-confessor-opuscula-theologica-et-polemica-confessor",
      "title": "Theological and Polemical Opuscula",
      "author": "Maximus Confessor",
      "year": 1860,
      "relation": "the same tradition"
    },
    {
      "id": "69c7978d6a0f3d112fafa0cf",
      "slug": "greek-kata-haireseon-oudoekonta-panarion-contra-octoginta-epiphanius",
      "title": "[Greek: Kata haireseon oudoekonta ... Panarion Contra octoginta haereses opus eximium, Pan",
      "author": "Epiphanius",
      "year": 1544,
      "relation": "the same tradition"
    },
    {
      "id": "69c8168e6c6f3cc53c848b0c",
      "slug": "opera-alexandrinus-2",
      "title": "Opera",
      "author": "Cyrillus Alexandrinus",
      "year": 1566,
      "relation": "the same tradition"
    }
  ],
  "Libanius|Epistulae": [
    {
      "id": "69ae6818b3b0e7bf712d6c63",
      "slug": "epistolographi-graeci-hercher",
      "title": "Greek Epistolographers",
      "author": "Rudolf Hercher",
      "year": 1873,
      "relation": "the same tradition"
    },
    {
      "id": "69c64199b463eebe7caac809",
      "slug": "greek-bioi-philosophon-kai-sophiston-de-vitis-philosophorum-eunapius",
      "title": "[Greek: Bioi philosophon kai sophiston] De vitis philosophorum et sophistarum",
      "author": "Eunapius",
      "year": 1596,
      "relation": "the same tradition"
    }
  ],
  "Maslama ibn al-Qasim al-Qurtubi|Rutbat al-Hakim": [
    {
      "id": "69d5ac2ed0bd3547a565582f",
      "slug": "the-catalogue-al-nadim",
      "title": "كتاب الفهرست (The Catalogue)",
      "author": "Ibn al-Nadim",
      "year": 1872,
      "relation": "the same tradition"
    }
  ],
  "Manuel I Komnenos and Michael Glykas|Imperatoris Manuel Comneni et Michael Glycæ disputatio": [
    {
      "id": "69bfcc7e8ab50eb88e8c5059",
      "slug": "christ-church-ms-49-psellus",
      "title": "Christ Church MS 49",
      "author": "Psellus, Michael; Zigavēnos, Euthymios, approximately 1050-approximately 1118 or 1120; Eugenikos, Markos, Saint, approximately 1392-1445?; Leo VI, Emperor of the East, 866-912; Monk Mathusalem; Lucaris, Cyril, 1572-1638; Hieromonk Metrophanes; Gregory I, Pope, approximately 540-604; Anonymous; Basileios Megalometos; Job Jasites, -approximately 1280; Gennadius II, Patriarch of Constantinople, approximately 1405-approximately 1472; Christodoulos; Athanasius, Saint, Patriarch of Alexandria, -373; Karampelas, Panagiotes Ch.; Brutus, pseudo",
      "year": 1725,
      "relation": "the same tradition"
    }
  ],
  "Libanius|Oration 30": [
    {
      "id": "69c64199b463eebe7caac809",
      "slug": "greek-bioi-philosophon-kai-sophiston-de-vitis-philosophorum-eunapius",
      "title": "[Greek: Bioi philosophon kai sophiston] De vitis philosophorum et sophistarum",
      "author": "Eunapius",
      "year": 1596,
      "relation": "the same tradition"
    },
    {
      "id": "69b2f4230e2f024dfbfbb5df",
      "slug": "themistii-orationes-estienne",
      "title": "The Orations of Themistius",
      "author": "Themistius (ed. Henri II Estienne)",
      "year": 1562,
      "relation": "the same tradition"
    }
  ],
  "Libanius|Orations": [
    {
      "id": "69c64199b463eebe7caac809",
      "slug": "greek-bioi-philosophon-kai-sophiston-de-vitis-philosophorum-eunapius",
      "title": "[Greek: Bioi philosophon kai sophiston] De vitis philosophorum et sophistarum",
      "author": "Eunapius",
      "year": 1596,
      "relation": "the same tradition"
    }
  ],
  "Maximus the Confessor|Capita theologica et oeconomica": [
    {
      "id": "69942e31d607f8e57e4b7df0",
      "slug": "de-variis-difficilibus-locis-ss-pp-dionysii-et-gregorii-oehler",
      "title": "On Various Difficult Passages of the Holy Fathers Dionysius and Gregory",
      "author": "Maximus the Confessor; ed. F. Oehler",
      "year": 1857,
      "relation": "by the same author"
    },
    {
      "id": "69942f83b2f6748db4ac128c",
      "slug": "maximus-confessor-opuscula-theologica-et-polemica-confessor",
      "title": "Theological and Polemical Opuscula",
      "author": "Maximus Confessor",
      "year": 1860,
      "relation": "by the same author"
    },
    {
      "id": "6a3f034a97e91e1768f69bc7",
      "slug": "ta-heuriskomena-panta-leontius",
      "title": "The Collected Works of Leontius of Byzantium",
      "author": "Leontius, Byzantinus, approximately 485- approximately543",
      "year": 1865,
      "relation": "the same tradition"
    }
  ],
  "Michael Psellos|Epistle on Chrysopoeia": [
    {
      "id": "69938921ce15387065946912",
      "slug": "michael-psellos-cambridge-university-library-ms-gg-6-10-psellos",
      "title": "On Plato and the Chaldaean Oracles",
      "author": "Michael Psellos",
      "year": 1525,
      "relation": "by the same author"
    },
    {
      "id": "69942f78b2f6748db4ac1229",
      "slug": "michael-psellos-and-john-kamateros-cambridge-trinity-psellos",
      "title": "Michael Psellos on Plato's Psychogony and John Kamateros on Astronomy",
      "author": "Michael Psellos",
      "year": 1550,
      "relation": "by the same author"
    },
    {
      "id": "699439cd6879ff0184cb9235",
      "slug": "philosophical-works-psellos",
      "title": "Philosophical Works",
      "author": "Michael Psellos",
      "year": 1050,
      "relation": "by the same author"
    }
  ],
  "Michael Psellos|Orationes forenses et acta": [
    {
      "id": "6953a8a877f38f6761bd3446",
      "slug": "chronographia-michael-psellus-psellus",
      "title": "Chronographia (Michael Psellus)",
      "author": "Michael Psellus",
      "year": 1926,
      "relation": "by the same author"
    },
    {
      "id": "699439cd6879ff0184cb9235",
      "slug": "philosophical-works-psellos",
      "title": "Philosophical Works",
      "author": "Michael Psellos",
      "year": 1050,
      "relation": "by the same author"
    },
    {
      "id": "69b3e609304c1c6b3950af5d",
      "slug": "michael-psellus-works-philosophical-and-theological-works-psellus",
      "title": "Compendium of the Art of Logic",
      "author": "Michael Psellus",
      "year": 1405,
      "relation": "by the same author"
    }
  ],
  "Michael Psellos|Commentary on the Chaldaean Oracles": [
    {
      "id": "699439cd6879ff0184cb9235",
      "slug": "philosophical-works-psellos",
      "title": "Philosophical Works",
      "author": "Michael Psellos",
      "year": 1050,
      "relation": "by the same author"
    },
    {
      "id": "69a979cbf3f3d2fb7de267b7",
      "slug": "magia-philosophica-oracula-chaldaica-patrizi",
      "title": "Philosophical Magic: The Chaldean Oracles",
      "author": "Francesco Patrizi",
      "year": 1593,
      "relation": "commentary on it"
    },
    {
      "id": "69b3e5c3304c1c6b3950a1ae",
      "slug": "in-platonis-theologiam-institutio-theologica-diadochus",
      "title": "On the Theology of Plato and Elements of Theology",
      "author": "Proclus Diadochus",
      "year": 1358,
      "relation": "the same tradition"
    }
  ],
  "Muhammad ibn Jarir al-Tabari|Tafsīr al-Ṭabarī": [
    {
      "id": "69d5ac2ed0bd3547a565582f",
      "slug": "the-catalogue-al-nadim",
      "title": "كتاب الفهرست (The Catalogue)",
      "author": "Ibn al-Nadim",
      "year": 1872,
      "relation": "the same tradition"
    },
    {
      "id": "69e961342beefe2f6f72a891",
      "slug": "muruj-al-dhahab-meadows-of-gold-al-masudi",
      "title": "مروج الذهب (Murūj al-Dhahab / Meadows of Gold)",
      "author": "Al-Masudi",
      "year": 1841,
      "relation": "the same tradition"
    }
  ],
  "Muhammad ibn Umail|Book of the Explanation of the Symbols": [
    {
      "id": "6a0a248b60700bc49f818309",
      "slug": "add-ms-25724-book-of-seven-climes-al-iraqi",
      "title": "Kitāb al-aqālīm al-sabʿah (The Book of the Seven Climes)",
      "author": "Abū al-Qāsim Muḥammad ibn Aḥmad al-ʿIrāqī al-Sīmāwī (active 13th c., Mamluk Egypt)",
      "year": 1750,
      "relation": "by the same author"
    }
  ],
  "Nicephorus Callistus Xanthopoulos|Ecclesiastical History": [
    {
      "id": "69942abcd607f8e57e4b4de1",
      "slug": "eusebius-werke-ii-die-kirchengeschichte-historia-caesarea",
      "title": "Church History (Historia Ecclesiastica)",
      "author": "Eusebius of Caesarea",
      "year": 1903,
      "relation": "the same tradition"
    },
    {
      "id": "69b21dca94025df5d2909ff2",
      "slug": "socrates-scholasticus-ecclesiastical-history-greek-hussey-hussey",
      "title": "Ecclesiastical History",
      "author": "Socrates Scholasticus; ed. Robert Hussey",
      "year": 1893,
      "relation": "the same tradition"
    },
    {
      "id": "69b21de094025df5d290a4b3",
      "slug": "historiae-ecclesiasticae-graece-et-latine-vol-1-reading-1720-reading",
      "title": "Ecclesiastical Histories in Greek and Latin, Vol. 1",
      "author": "Eusebius; Socrates Scholasticus; Sozomen; ed. Henricus Valesius; Gulielmus Reading",
      "year": 1720,
      "relation": "the same tradition"
    }
  ],
  "Olympiodorus|In Gorgiam": [
    {
      "id": "69b52cceb3537347e51e316d",
      "slug": "olympiodorus-scholia-on-aristotle-s-meteorology-neoplatonic-aristotle",
      "title": "Olympiodorus, Scholia on Aristotle's Meteorology (Neoplatonic)",
      "author": "Olympiodorus; Aristotle",
      "year": 1450,
      "relation": "by the same author"
    },
    {
      "id": "6a0856a515c643eb1af596e8",
      "slug": "olympiodorou-philosophou-alexandreos-eis-ta-meteora-tou-aris",
      "title": "Olympiodōrou philosophou Alexandreōs eis ta Meteōra tou Aristotelous ypomnemata. Ioannou G",
      "author": "Olympiodorus : Alexandrinus filosofo (filosofo)",
      "year": 1551,
      "relation": "by the same author"
    },
    {
      "id": "69b43d4dee0300187dbd1906",
      "slug": "porphyry-isagoge-neoplatonic-commentaries-proclus-ammonius-ammonius",
      "title": "Porphyry Isagoge & Neoplatonic Commentaries (Proclus, Ammonius)",
      "author": "Porphyry; Proclus; Ammonius",
      "year": 1350,
      "relation": "the same tradition"
    }
  ],
  "Olympiodorus|Life of Plato": [
    {
      "id": "6952ca6e77f38f6761bc3fb2",
      "slug": "life-of-proclus-by-marinus-neapolis",
      "title": "The Life of Proclus",
      "author": "Marinus of Neapolis",
      "year": 1814,
      "relation": "the same tradition"
    },
    {
      "id": "69a5e5e385fa13e734e41894",
      "slug": "procli-opera-grec-1839-proclus",
      "title": "Commentary on Plato's Timaeus",
      "author": "Proclus",
      "year": 1360,
      "relation": "the same tradition"
    },
    {
      "id": "69a5e60885fa13e734e42186",
      "slug": "procli-in-platonis-alcibiadem-commentarius-barocci-140-proclus",
      "title": "Commentary on Plato's Alcibiades",
      "author": "Proclus",
      "year": 1450,
      "relation": "the same tradition"
    }
  ],
  "Origen|Commentary on Luke": [
    {
      "id": "6990633fef12272ffdc90a16",
      "slug": "contra-celsum-libri-octo-1658-edition-origen",
      "title": "Against Celsus",
      "author": "Origen",
      "year": 1658,
      "relation": "by the same author"
    },
    {
      "id": "69942a7f045dfc482ad772e7",
      "slug": "philocalia-editio-princeps-tarinus-1618-origen",
      "title": "Philocalia (First Edition, Tarinus 1618)",
      "author": "Origen",
      "year": 1618,
      "relation": "contains excerpts"
    },
    {
      "id": "6a0c53fc99c52ea845a06630",
      "slug": "origen-s-homilies-on-leviticus-latin-rufinus",
      "title": "Origen's Homilies on Leviticus (Latin)",
      "author": "Origen (trans. Rufinus)",
      "year": 1300,
      "relation": "by the same author"
    }
  ],
  "Paul the Apostle|Epistle to the Ephesians": [
    {
      "id": "69b630131c1c21a3737fd9ca",
      "slug": "commentarii-in-epistolam-d-pauli-ad-ephesios-facili-et-marti-2",
      "title": "{Commentarii in Epistolam D. Pauli ad Ephesios, facili et perspicua methodo conscripti. A ",
      "author": "Marti, Benedikt dit Aretius",
      "year": 1583,
      "relation": "commentary on it"
    },
    {
      "id": "69b65a6f18b87551bfd02a55",
      "slug": "isagoge-ad-lectionem-epistolarum-divi-pauli-apostoli-qua-aretius",
      "title": "Isagoge ad lectionem Epistolarum Divi Pauli apostoli, qua compositionis oeconomia, et germ",
      "author": "Aretius, Benedictus",
      "year": 1579,
      "relation": "commentary on it"
    }
  ],
  "Porphyry|Introduction to the Tetrabiblos": [
    {
      "id": "69906057ef12272ffdc8ce25",
      "slug": "tetrabiblos-trans",
      "title": "Tetrabiblos (The Four Books)",
      "author": "Ptolemy; Proclus (paraphrase); J. M. Ashmand (trans.)",
      "year": 1822,
      "relation": "commentary on it"
    },
    {
      "id": "69b4c05a86a5921d5bc43469",
      "slug": "proclus-astronomical-calculations-hypotyposis-proclus",
      "title": "Proclus, Astronomical Calculations (Hypotyposis)",
      "author": "Proclus",
      "year": 1450,
      "relation": "the same tradition"
    },
    {
      "id": "69b4c05e86a5921d5bc434b7",
      "slug": "theon-of-smyrna-exposition-on-astronomy-smyrna",
      "title": "Theon of Smyrna, Exposition on Astronomy",
      "author": "Theon of Smyrna",
      "year": 1350,
      "relation": "the same tradition"
    }
  ],
  "Proclus|On the Hieratic Art of the Hellenes": [
    {
      "id": "6952ca6a77f38f6761bc3f19",
      "slug": "elements-of-theology-and-physics-proclus",
      "title": "Elements of Theology and Physics",
      "author": "Proclus",
      "year": 1618,
      "relation": "by the same author"
    },
    {
      "id": "6952ca6e77f38f6761bc3fb2",
      "slug": "life-of-proclus-by-marinus-neapolis",
      "title": "The Life of Proclus",
      "author": "Marinus of Neapolis",
      "year": 1814,
      "relation": "by the same author"
    },
    {
      "id": "69d13d751c2a66dc094b168d",
      "slug": "de-mysteriis-liber-parthey-critical-edition-parthey",
      "title": "On the Mysteries",
      "author": "Iamblichus; ed. Gustav Parthey",
      "year": 1857,
      "relation": "the same tradition"
    }
  ],
  "Pseudo-Plutarch|De vita et poesi Homeri": [
    {
      "id": "69938a885d28b693146cec8f",
      "slug": "bodleian-library-ms-barocci-162-proclus",
      "title": "Commentaries on Plato's Alcibiades I and Homer's Iliad",
      "author": "Proclus",
      "year": 1450,
      "relation": "the same tradition"
    },
    {
      "id": "69b2f4300e2f024dfbfbbc64",
      "slug": "homeri-et-hesiodi-certamen-batrachomyomachia-homer",
      "title": "The Contest of Homer and Hesiod; The Battle of the Frogs and Mice",
      "author": "Homer, Hesiod (ed. Henri II Estienne)",
      "year": 1573,
      "relation": "the same tradition"
    },
    {
      "id": "6a08561515c643eb1af57ce0",
      "slug": "scholia-palaia-te-kai-panu-ophelima-eis-ten-tou-omerou-iliad",
      "title": "Scholia palaia te, kai panu ophelima eis ten tou Omerou Iliada, kai eis ten Odyssea. Inter",
      "author": "Didymus : Chalcenterus",
      "year": 1521,
      "relation": "the same tradition"
    }
  ],
  "Sahl al-Tustari|Tafsir Al-Tustari": [
    {
      "id": "69b63e7f2a1dde00d5a9e314",
      "slug": "al-risala-al-qushayriyya-treatise-on-sufism-al-qushayri",
      "title": "Al-Risala al-Qushayriyya (Treatise on Sufism)",
      "author": "Al-Qushayri",
      "year": 1870,
      "relation": "the same tradition"
    },
    {
      "id": "69e8b2a72ff2a8dc09e7860d",
      "slug": "ihya-ulum-al-din-al-ghazali",
      "title": "إحياء علوم الدين (Iḥyāʾ ʿUlūm al-Dīn)",
      "author": "Al-Ghazali",
      "year": 1402,
      "relation": "the same tradition"
    }
  ],
  "Ptolemy (Gnostic)|Letter to Flora": [
    {
      "id": "69ae939373fc4632370d4aec",
      "slug": "koptisch-gnostische-schriften-schmidt",
      "title": "Coptic Gnostic Writings",
      "author": "Carl Schmidt",
      "year": 1905,
      "relation": "the same tradition"
    },
    {
      "id": "69c884a06c6f3cc53c8599e5",
      "slug": "pistis-sophia-a-gnostic-gospel-with-extracts-from-the-books",
      "title": "Pistis sophia. A gnostic gospel (with extracts from the books of the saviour appended)",
      "author": "Unknown",
      "year": 1896,
      "relation": "the same tradition"
    }
  ],
  "Solomon|Proverbs": [
    {
      "id": "69c1bc3a8522835be8461fe6",
      "slug": "excerpts-from-the-hebrew-bible-mishnah-and-gemara-anonymous",
      "title": "Excerpts from the Hebrew Bible, Mishnah and Gemara (Gaster Hebrew MS 2041)",
      "author": "Anonymous",
      "year": 1850,
      "relation": "contains excerpts"
    },
    {
      "id": "6a3f02b497e91e1768f67fa9",
      "slug": "a-critical-and-exegetical-commentary-on-the-book-of-proverbs-toy",
      "title": "A critical and exegetical commentary on the book of Proverbs",
      "author": "Toy, Crawford Howell, 1836-1919",
      "year": 1899,
      "relation": "commentary on it"
    }
  ],
  "Stephanos of Alexandria|On the Great and Sacred Art of Making Gold": [
    {
      "id": "6994383a6879ff0184cb803a",
      "slug": "collection-des-anciens-alchimistes-grecs-vols-2-3-berthelot",
      "title": "Collection of the Ancient Greek Alchemists, Vols. 2-3",
      "author": "Marcellin Berthelot",
      "year": 1888,
      "relation": "contains excerpts"
    },
    {
      "id": "69a979e9daf647306a736c91",
      "slug": "collection-des-anciens-alchimistes-grecs-vol-3-berthelot",
      "title": "Collection of the Ancient Greek Alchemists, Volume 3",
      "author": "Marcellin Berthelot",
      "year": 1888,
      "relation": "contains excerpts"
    },
    {
      "id": "69b4c04d978ca9526eda33f7",
      "slug": "sacred-art-of-the-philosophers-greek-alchemical-anthology-various",
      "title": "Sacred Art of the Philosophers (Greek alchemical anthology)",
      "author": "Various",
      "year": 1495,
      "relation": "the same tradition"
    }
  ],
  "Theodore Abu Qurra|Maymar fī Wuǧūd al-ḫāliq wa-d-dīn al-qawīm": [
    {
      "id": "6a3f035997e91e1768f6a29a",
      "slug": "theodore-abu-qurrah-mayamir-thawdurus-abi-qurrah-usquf",
      "title": "Treatises of Theodore Abu Qurrah",
      "author": "Theodore Abu Qurrah",
      "year": 1904,
      "relation": "by the same author"
    }
  ],
  "Thomas Digges|A Perfit Description of the Coelestiall Orbes": [
    {
      "id": "69a5f6d51cf742c360414674",
      "slug": "pantometria-a-geometrical-treatize-of-measuring-digges",
      "title": "Pantometria — A Geometrical Treatize of Measuring",
      "author": "Leonard Digges; Thomas Digges",
      "year": 1591,
      "relation": "by the same author"
    },
    {
      "id": "6990689d8034a3640265bc68",
      "slug": "cosmographicus-liber-apian",
      "title": "Cosmographic Book (Cosmographicus Liber)",
      "author": "Peter Apian",
      "year": 1524,
      "relation": "the same tradition"
    }
  ],
  "Virgilius Maro Grammaticus|Opera Omnia": [
    {
      "id": "69dbca6e1040d1d5e20ac348",
      "slug": "etymologiae-isidorus-hispalensis-1",
      "title": "Etymologiae",
      "author": "Isidorus Hispalensis",
      "year": 1489,
      "relation": "the same tradition"
    },
    {
      "id": "69dbca711040d1d5e20ac4f7",
      "slug": "etymologiae-isidorus-hispalensis-2",
      "title": "Etymologiae",
      "author": "Isidorus Hispalensis",
      "year": 1499,
      "relation": "the same tradition"
    }
  ],
  "Timaeus of Locri|On the Nature of the Cosmos and the Soul": [
    {
      "id": "69557474f63a7571091734e4",
      "slug": "commentarius-in-platonis-timaeum-diadochus",
      "title": "Commentary on Plato's Timaeus",
      "author": "Proclus Diadochus",
      "year": 1820,
      "relation": "commentary on it"
    },
    {
      "id": "699051d18d19cbc90d9d5136",
      "slug": "commentary-on-platos-timaeus-chalcidius",
      "title": "Commentary on Platos Timaeus",
      "author": "Chalcidius",
      "year": 1532,
      "relation": "commentary on it"
    },
    {
      "id": "69b51eba47b06ecd581960d3",
      "slug": "sebastiani-foxij-morzilli-hispalensis-in-platonis-timaeum-morcillo",
      "title": "Commentary on Plato's Timaeus",
      "author": "Morcillo, Sebastián Fox",
      "year": 1554,
      "relation": "commentary on it"
    }
  ],
  "Zenobius|Paroemiographi Graeci": [
    {
      "id": "69b304445facc83a9a3dbf99",
      "slug": "proverbia-graeca-apostolius",
      "title": "Greek Proverbs",
      "author": "Michael Apostolius",
      "year": 1619,
      "relation": "the same tradition"
    },
    {
      "id": "6a3f035f97e91e1768f6a310",
      "slug": "corpus-paroemiographorum-graecorum-ediderunt-e-l-a-leutsch-leutsch",
      "title": "Corpus of Greek Proverb Writers",
      "author": "Leutsch, Ernst Ludwig von, 1808-1887",
      "year": 1839,
      "relation": "the same tradition"
    }
  ],
  "Zosimus of Panopolis|Mushaf as-suwar": [
    {
      "id": "6953619d9c494f9f9f042608",
      "slug": "majmu-nafis-fi-al-kimiya-jabir-ibn-hayyan-hayyan",
      "title": "A Precious Collection on Alchemy",
      "author": "Jabir ibn Hayyan",
      "year": 800,
      "relation": "the same tradition"
    },
    {
      "id": "6a0a248b60700bc49f818309",
      "slug": "add-ms-25724-book-of-seven-climes-al-iraqi",
      "title": "Kitāb al-aqālīm al-sabʿah (The Book of the Seven Climes)",
      "author": "Abū al-Qāsim Muḥammad ibn Aḥmad al-ʿIrāqī al-Sīmāwī (active 13th c., Mamluk Egypt)",
      "year": 1750,
      "relation": "the same tradition"
    }
  ],
  "Anonymous|Sepher ha-Razim": [
    {
      "id": "69b3e67c304c1c6b3950b7c3",
      "slug": "collection-of-kabbalah-and-hekhalot-texts-ms-michael-9-various",
      "title": "Book of Creation and Jewish Mystical Texts",
      "author": "Various",
      "year": 1350,
      "relation": "the same tradition"
    },
    {
      "id": "69c1bae58522835be845b540",
      "slug": "incantations-and-amulets-anonymous",
      "title": "Incantations and amulets (Gaster Hebrew MS 177)",
      "author": "Anonymous",
      "year": 1650,
      "relation": "the same tradition"
    },
    {
      "id": "69c1bbcf8522835be8460a04",
      "slug": "fragments-from-magical-manuscripts-anonymous",
      "title": "Fragments from magical manuscripts (Gaster Hebrew MS 1634)",
      "author": "Anonymous",
      "year": 1750,
      "relation": "the same tradition"
    }
  ]
};
