/**
 * The PAGE a SHWEP citation points at, inside an edition we hold — so a reader lands on
 * the passage instead of the front of a 500-page folio. Keyed "episode|author|work".
 *
 * Every entry was verified against the real page text (Mongo, wrapper-stripped) by a
 * second model pass that was told to default to "no": an unverified deep link is a
 * fabricated citation. Citations that could not be confirmed are simply absent here and
 * fall back to the volume-level link.
 * Generated by scripts/enrichment/shwep-resolve-loci.mjs (gemini-3.1-flash-lite).
 */
export interface ShwepResolvedLocus {
  bookId: string;
  slug: string | null;
  title: string;
  pageId: string;
  pageNumber: number;
  similarity: number;
  why: string;
}
export const SHWEP_RESOLVED_LOCI: Record<string, ShwepResolvedLocus> = {
  "7|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961c06",
    "pageNumber": 367,
    "similarity": 0.797,
    "why": "The text explicitly discusses rational soul in sleep."
  },
  "7|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cf08",
    "pageNumber": 113,
    "similarity": 0.738,
    "why": "The text explicitly discusses signs of true dreams."
  },
  "7|Homer|Odyssey": {
    "bookId": "69e7478d85f786e884a48a87",
    "slug": "homeri-odyssea-homer",
    "title": "Ὁμήρου Ὀδύσσεια (Homeri Odyssea)",
    "pageId": "69e7478d85f786e884a48cc6",
    "pageNumber": 575,
    "similarity": 0.736,
    "why": "The text explicitly describes the two dream gates."
  },
  "7|Marcus Tullius Cicero|De divinatione": {
    "bookId": "69ac9be7dc7bbeb920621588",
    "slug": "de-senectute-de-amicitia-de-divinatione-cicero",
    "title": "On Old Age, On Friendship, On Divination",
    "pageId": "69ac9be7dc7bbeb9206216bb",
    "pageNumber": 307,
    "similarity": 0.809,
    "why": "The text explicitly discusses Posidonius's dream theories."
  },
  "18|Diogenes Laërtius|Lives of the Eminent Philosophers": {
    "bookId": "6993882874305116d72cf9f3",
    "slug": "pal-gr-182-laertius",
    "title": "Pal.gr.182",
    "pageId": "6993882874305116d72cfb1c",
    "pageNumber": 297,
    "similarity": 0.796,
    "why": "Page explicitly mentions Aristoxenus and Pythagorean doctrin"
  },
  "67|Apuleius|Metamorphoses": {
    "bookId": "69af21d07c27d4b637feddd1",
    "slug": "metamorphoseon-libri-xi-apuleius",
    "title": "The Golden Ass (Metamorphoses)",
    "pageId": "69af21d07c27d4b637fede12",
    "pageNumber": 65,
    "similarity": 0.74,
    "why": "The text explicitly identifies Lucius as relative."
  },
  "69|Clement of Alexandria|Stromata": {
    "bookId": "69942a51045dfc482ad766f4",
    "slug": "clemens-alexandrinus-ii-stromata-i-vi-gcs-stahlin-alexandria",
    "title": "Clement of Alexandria II: Stromata I-VI",
    "pageId": "69942a51045dfc482ad76745",
    "pageNumber": 81,
    "similarity": 0.715,
    "why": "The text mentions her soul in the moon."
  },
  "70|Valerius Maximus|Facta et Dicta Memorabilia": {
    "bookId": "69af2390285bd73604374574",
    "slug": "valerius-maximus-factorum-et-dictorum-memorabilium-libri-ix-maximus",
    "title": "Valerius Maximus: Memorable Deeds and Sayings",
    "pageId": "69af2390285bd736043745bd",
    "pageNumber": 73,
    "similarity": 0.787,
    "why": "The text explicitly describes summoning Aesculapius for plag"
  },
  "71|Aristotle|Parva naturalia": {
    "bookId": "69b21bb5429e087c6f862f05",
    "slug": "aristotelis-opera-vol-3-de-anima-parva-naturalia-aristotle",
    "title": "Aristotle's Works, Volume 3: History of Animals and Parva Naturalia",
    "pageId": "69b21bb5429e087c6f86313a",
    "pageNumber": 565,
    "similarity": 0.717,
    "why": "Page discusses dream mechanisms and sensory perception."
  },
  "71|Juvenal|Satires": {
    "bookId": "69b2210656715b0e3247421f",
    "slug": "juvenal-and-persius-saturae-aldine-press-persius",
    "title": "Satires of Juvenal and Persius",
    "pageId": "69b2210656715b0e3247425c",
    "pageNumber": 61,
    "similarity": 0.705,
    "why": "The text explicitly mentions Jewish dream-selling women."
  },
  "73|Apuleius|Metamorphoses": {
    "bookId": "69af21d07c27d4b637feddd1",
    "slug": "metamorphoseon-libri-xi-apuleius",
    "title": "The Golden Ass (Metamorphoses)",
    "pageId": "69af21d07c27d4b637fedf33",
    "pageNumber": 354,
    "similarity": 0.788,
    "why": "The text describes Lucius' initiation into Isis."
  },
  "74|Plato|Timaeus": {
    "bookId": "69905f1140bc3a0478efa1d3",
    "slug": "timaeus-greek-text-with-commentary-archer-hind",
    "title": "Timaeus (Greek text with commentary)",
    "pageId": "69905f1140bc3a0478efa236",
    "pageNumber": 99,
    "similarity": 0.581,
    "why": "The page contains the cited passage text."
  },
  "74|Plato|Phaedrus": {
    "bookId": "6953cee877f38f6761be5dd8",
    "slug": "plato-euthyphro-apology-crito-phaedo-phaedrus-plato",
    "title": "Plato Euthyphro, Apology, Crito, Phaedo, Phaedrus",
    "pageId": "6953cee977f38f6761be6014",
    "pageNumber": 572,
    "similarity": 0.755,
    "why": "Page contains 271a-b, part of the cited range."
  },
  "74|Apuleius|Apologia": {
    "bookId": "69af217f7c27d4b637fed9e0",
    "slug": "apologia-sive-pro-se-de-magia-liber-apuleius",
    "title": "Apologia (A Discourse on Magic)",
    "pageId": "69af217f7c27d4b637feda81",
    "pageNumber": 161,
    "similarity": 0.74,
    "why": "Page contains 93.3-5 regarding Pudentilla's wealth."
  },
  "74|Apuleius|Florida": {
    "bookId": "6953c6fe77f38f6761bda5c2",
    "slug": "works-of-apuleius-golden-ass-god-of-socrates-florida-apuleius",
    "title": "The Works of Apuleius",
    "pageId": "6953c6fe77f38f6761bda74f",
    "pageNumber": 397,
    "similarity": 0.709,
    "why": "The text describes the proconsul's binding sentence."
  },
  "76|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cf2c",
    "pageNumber": 149,
    "similarity": 0.802,
    "why": "Page discusses animating statues and divine inspiration."
  },
  "76|Augustine of Hippo|City of God": {
    "bookId": "699062f5ef12272ffdc8e9d5",
    "slug": "de-civitate-dei-augustine",
    "title": "De Civitate Dei",
    "pageId": "699062f5ef12272ffdc8eace",
    "pageNumber": 249,
    "similarity": 0.765,
    "why": "The text explicitly discusses theurgy and magicians."
  },
  "76|Anonymous|Chaldaean Oracles": {
    "bookId": "69924f2a09c5da0cf50d7063",
    "slug": "the-chaldaean-oracles-mead",
    "title": "The Chaldaean Oracles",
    "pageId": "69924f2b09c5da0cf50d70b6",
    "pageNumber": 83,
    "similarity": 0.779,
    "why": "Page explicitly discusses the herd and fate."
  },
  "78|Proclus|Commentary on Plato's Timaeus": {
    "bookId": "69a5e5e385fa13e734e41894",
    "slug": "procli-opera-grec-1839-proclus",
    "title": "Commentary on Plato's Timaeus",
    "pageId": "69a5e5e385fa13e734e419af",
    "pageNumber": 283,
    "similarity": 0.737,
    "why": "The text explicitly discusses Numenius's three gods."
  },
  "78|Clement of Alexandria|Stromata": {
    "bookId": "69942a51045dfc482ad766f4",
    "slug": "clemens-alexandrinus-ii-stromata-i-vi-gcs-stahlin-alexandria",
    "title": "Clement of Alexandria II: Stromata I-VI",
    "pageId": "69942a51045dfc482ad76775",
    "pageNumber": 129,
    "similarity": 0.746,
    "why": "The page explicitly quotes Numenius at 150.4."
  },
  "78|Origen|Contra Celsum": {
    "bookId": "69942a87045dfc482ad77805",
    "slug": "opera-omnia-xviii-contra-celsum-i-iv-lommatzsch-origen",
    "title": "Complete Works XVIII: Against Celsus I-IV (Lommatzsch)",
    "pageId": "69942a87045dfc482ad77836",
    "pageNumber": 49,
    "similarity": 0.772,
    "why": "The page explicitly cites Celsus I.15 and Numenius."
  },
  "79|Plotinus|Enneads": {
    "bookId": "69a5e5d91d73f9668388ef2b",
    "slug": "plotini-enneades-13th-c-copy-a-plotinus",
    "title": "The Enneads",
    "pageId": "69a5e5d91d73f9668388f17c",
    "pageNumber": 593,
    "similarity": 0.732,
    "why": "The text discusses the One's act of thinking."
  },
  "79|Proclus|Commentary on Plato's Timaeus": {
    "bookId": "69a5e5e385fa13e734e41894",
    "slug": "procli-opera-grec-1839-proclus",
    "title": "Commentary on Plato's Timaeus",
    "pageId": "69a5e5e385fa13e734e419af",
    "pageNumber": 283,
    "similarity": 0.759,
    "why": "The text explicitly discusses Numenius' three gods."
  },
  "83|Clement of Alexandria|Stromata": {
    "bookId": "69942a51045dfc482ad766f4",
    "slug": "clemens-alexandrinus-ii-stromata-i-vi-gcs-stahlin-alexandria",
    "title": "Clement of Alexandria II: Stromata I-VI",
    "pageId": "69942a51045dfc482ad767c7",
    "pageNumber": 211,
    "similarity": 0.643,
    "why": "The page contains the soul-inn passage."
  },
  "84|Origen|Commentary on Romans": {
    "bookId": "69942b2ad607f8e57e4b70c5",
    "slug": "patrologia-graeca-vol-12-origenes-ii-origen",
    "title": "Patrologia Graeca vol. 12: Origenes II",
    "pageId": "69942b2bd607f8e57e4b7300",
    "pageNumber": 571,
    "similarity": 0.712,
    "why": "The text matches the cited commentary passage."
  },
  "89|Claudius Ptolemy|Tetrabiblos": {
    "bookId": "6990532bd7712f78163cd522",
    "slug": "tetrabiblos-ptolemy",
    "title": "Tetrabiblos",
    "pageId": "6990532bd7712f78163cd53c",
    "pageNumber": 26,
    "similarity": 0.736,
    "why": "Text discusses preventative art and medical-astrological uti"
  },
  "93|Clement of Alexandria|Stromata": {
    "bookId": "69942a51045dfc482ad766f4",
    "slug": "clemens-alexandrinus-ii-stromata-i-vi-gcs-stahlin-alexandria",
    "title": "Clement of Alexandria II: Stromata I-VI",
    "pageId": "69942a51045dfc482ad76892",
    "pageNumber": 414,
    "similarity": 0.781,
    "why": "Page contains V.79.1 and discusses God's ineffability."
  },
  "93|Photius|Bibliotheca": {
    "bookId": "6955801057e3b773024f5030",
    "slug": "bibliotheca-myriobiblon-photius-i",
    "title": "The Library (Bibliotheca)",
    "pageId": "6955801057e3b773024f5095",
    "pageNumber": 101,
    "similarity": 0.784,
    "why": "Page explicitly discusses Clement's subordinationist Hypotyp"
  },
  "96|Hippolytus of Rome|Adversus haereses": {
    "bookId": "69ac9bbf99d9a0170d090df4",
    "slug": "refutation-of-all-heresies-vol-2-rome",
    "title": "Refutation of All Heresies, Vol. 2",
    "pageId": "69ac9bbf99d9a0170d090e3a",
    "pageNumber": 70,
    "similarity": 0.772,
    "why": "Page discusses Basilides' system and Sonhood."
  },
  "96|Apuleius|De deo Socratis": {
    "bookId": "6990633bef12272ffdc90769",
    "slug": "de-deo-socratis-apuleius",
    "title": "On the God of Socrates",
    "pageId": "6990633bef12272ffdc90777",
    "pageNumber": 14,
    "similarity": 0.789,
    "why": "The text explicitly discusses the ineffable parent."
  },
  "99|Pliny the Elder|Natural History": {
    "bookId": "69afd0df775a23a98ee93a30",
    "slug": "historia-naturalis-elder",
    "title": "Natural History",
    "pageId": "69afd0df775a23a98ee93be0",
    "pageNumber": 432,
    "similarity": 0.661,
    "why": "The text explicitly mentions Moses and magic."
  },
  "99|Origen|Homilies on Joshua": {
    "bookId": "69942b2ad607f8e57e4b70c5",
    "slug": "patrologia-graeca-vol-12-origenes-ii-origen",
    "title": "Patrologia Graeca vol. 12: Origenes II",
    "pageId": "69942b2bd607f8e57e4b7296",
    "pageNumber": 465,
    "similarity": 0.698,
    "why": "The text explicitly discusses innate power of names."
  },
  "100|Clement of Alexandria|Stromata": {
    "bookId": "69942a51045dfc482ad766f4",
    "slug": "clemens-alexandrinus-ii-stromata-i-vi-gcs-stahlin-alexandria",
    "title": "Clement of Alexandria II: Stromata I-VI",
    "pageId": "69942a51045dfc482ad768d9",
    "pageNumber": 485,
    "similarity": 0.789,
    "why": "The text explicitly mentions forty-two books of Hermes."
  },
  "100|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cf68",
    "pageNumber": 209,
    "similarity": 0.718,
    "why": "The text explicitly cites Seleucus and Manetho."
  },
  "100|Homer|Iliad": {
    "bookId": "69e7478285f786e884a487d4",
    "slug": "homeri-ilias-homer",
    "title": "Ὁμήρου Ἰλιάς (Homeri Ilias)",
    "pageId": "69e7478385f786e884a48a6b",
    "pageNumber": 663,
    "similarity": 0.766,
    "why": "The page contains the cited passage."
  },
  "101|Anonymous|Mithras Liturgy": {
    "bookId": "6992541959cdabeb78f1bd06",
    "slug": "eine-mithrasliturgie-dieterich",
    "title": "A Mithraic Liturgy",
    "pageId": "6992541a59cdabeb78f1bdf7",
    "pageNumber": 240,
    "similarity": 0.753,
    "why": "Discusses the Mithras liturgy and scholarly debate."
  },
  "101|Paul the Apostle|Second Epistle to the Corinthians": {
    "bookId": "69938976ce15387065946e02",
    "slug": "basel-universitatsbibliothek-an-iii-11-commentary",
    "title": "Basel, Universitätsbibliothek, AN III 11",
    "pageId": "69938976ce15387065946fc1",
    "pageNumber": 447,
    "similarity": 0.783,
    "why": "The text explicitly quotes 2 Corinthians 12:2-4."
  },
  "107|Plato|Theaetetus": {
    "bookId": "6953ce9577f38f6761be535d",
    "slug": "plato-theaetetus-sophist-plato",
    "title": "Plato: Theaetetus and Sophist",
    "pageId": "6953ce9577f38f6761be53e6",
    "pageNumber": 137,
    "similarity": 0.756,
    "why": "The page explicitly discusses assimilation to God."
  },
  "110|Clement of Alexandria|Stromata": {
    "bookId": "69942a51045dfc482ad766f4",
    "slug": "clemens-alexandrinus-ii-stromata-i-vi-gcs-stahlin-alexandria",
    "title": "Clement of Alexandria II: Stromata I-VI",
    "pageId": "69942a51045dfc482ad76745",
    "pageNumber": 81,
    "similarity": 0.715,
    "why": "The text mentions her soul in the moon."
  },
  "110|Plato|Phaedrus": {
    "bookId": "6953cee877f38f6761be5dd8",
    "slug": "plato-euthyphro-apology-crito-phaedo-phaedrus-plato",
    "title": "Plato Euthyphro, Apology, Crito, Phaedo, Phaedrus",
    "pageId": "6953cee977f38f6761be5fc0",
    "pageNumber": 488,
    "similarity": 0.768,
    "why": "The text discusses divine madness and prophecy."
  },
  "112|Proclus|Commentary on Plato's Timaeus": {
    "bookId": "69a5e5e385fa13e734e41894",
    "slug": "procli-opera-grec-1839-proclus",
    "title": "Commentary on Plato's Timaeus",
    "pageId": "69a5e5e385fa13e734e41c97",
    "pageNumber": 1027,
    "similarity": 0.73,
    "why": "Page discusses the undescended soul and Plotinus."
  },
  "114|Plato|Theaetetus": {
    "bookId": "6953ce9577f38f6761be535d",
    "slug": "plato-theaetetus-sophist-plato",
    "title": "Plato: Theaetetus and Sophist",
    "pageId": "6953ce9577f38f6761be53e6",
    "pageNumber": 137,
    "similarity": 0.753,
    "why": "The text explicitly mentions assimilation to God."
  },
  "115|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961bad",
    "pageNumber": 278,
    "similarity": 0.762,
    "why": "The text discusses the Good at 505e-506b."
  },
  "115|Plato|Phaedrus": {
    "bookId": "6953cee877f38f6761be5dd8",
    "slug": "plato-euthyphro-apology-crito-phaedo-phaedrus-plato",
    "title": "Plato Euthyphro, Apology, Crito, Phaedo, Phaedrus",
    "pageId": "6953cee977f38f6761be6026",
    "pageNumber": 590,
    "similarity": 0.758,
    "why": "The text explicitly discusses writing and dialectic."
  },
  "115|Plato|Symposium": {
    "bookId": "69a976a1e12635ded71c4fd9",
    "slug": "the-symposium-of-plato-bury",
    "title": "The Symposium of Plato",
    "pageId": "69a976a1e12635ded71c5044",
    "pageNumber": 107,
    "similarity": 0.786,
    "why": "The text explicitly discusses two Aphrodites."
  },
  "116|Plotinus|Enneads": {
    "bookId": "69a5e5d91d73f9668388ef2b",
    "slug": "plotini-enneades-13th-c-copy-a-plotinus",
    "title": "The Enneads",
    "pageId": "69a5e5d91d73f9668388ef90",
    "pageNumber": 101,
    "similarity": 0.774,
    "why": "The text discusses matter, necessity, and evil."
  },
  "120|Gregory of Nazianzus|Orations": {
    "bookId": "69b2222608069e96e8432997",
    "slug": "gregory-of-nazianzus-orationes-selectae-xvi-aldine-press-nazianzus",
    "title": "Gregory of Nazianzus, Sixteen Selected Orations",
    "pageId": "69b2222608069e96e8432a6e",
    "pageNumber": 215,
    "similarity": 0.729,
    "why": "The text describes Julian's initiation into mysteries."
  },
  "120|Nonnos of Panopolis|Dionysiaka": {
    "bookId": "69938d615d28b693146cee47",
    "slug": "dionysiaca-cunaeus-edition-panopolis",
    "title": "Dionysiaca (Cunaeus Edition)",
    "pageId": "69938d615d28b693146cf2a0",
    "pageNumber": 1113,
    "similarity": 0.778,
    "why": "The text explicitly mentions Mithras and Phaethon."
  },
  "122|Marinus of Neapolis|Life of Proclus": {
    "bookId": "6952ca6e77f38f6761bc3fb2",
    "slug": "life-of-proclus-by-marinus-neapolis",
    "title": "The Life of Proclus",
    "pageId": "6952ca6e77f38f6761bc401e",
    "pageNumber": 108,
    "similarity": 0.803,
    "why": "The text explicitly mentions Proclus viewing Hecate."
  },
  "122|Hierocles of Alexandria|Commentary on the Golden Verses of Pythagoras": {
    "bookId": "699389a6ce15387065947dc0",
    "slug": "hieroclis-expositio-versuum-pythagorae-qui-aurei-dicuntur-trismegistus",
    "title": "Hieroclis Expositio versuum Pythagorae qui aurei dicuntur . Hermes Trismegistus . Adde etiam Hermes Trismegistus, Apuleio interprete",
    "pageId": "699389a7ce15387065947e7f",
    "pageNumber": 191,
    "similarity": 0.749,
    "why": "The text explicitly discusses purification of the body."
  },
  "125|Eunapius|Lives of the Sophists": {
    "bookId": "699437c36879ff0184cb7381",
    "slug": "vitae-sophistarum-et-fragmenta-historiarum-sardis",
    "title": "Lives of the Sophists and Fragments of the Histories",
    "pageId": "699437c36879ff0184cb73d4",
    "pageNumber": 83,
    "similarity": 0.771,
    "why": "Page describes Porphyry's exorcism and fellow students."
  },
  "125|Socrates of Constantinople|Ecclesiastical History": {
    "bookId": "69b21dca94025df5d2909ff2",
    "slug": "socrates-scholasticus-ecclesiastical-history-greek-hussey-hussey",
    "title": "Ecclesiastical History",
    "pageId": "69b21dca94025df5d290a028",
    "pageNumber": 54,
    "similarity": 0.741,
    "why": "Page mentions Porphyry's infamy and Arius's comparison."
  },
  "126|Eunapius|Lives of the Sophists": {
    "bookId": "699437c36879ff0184cb7381",
    "slug": "vitae-sophistarum-et-fragmenta-historiarum-sardis",
    "title": "Lives of the Sophists and Fragments of the Histories",
    "pageId": "699437c36879ff0184cb73d3",
    "pageNumber": 82,
    "similarity": 0.709,
    "why": "Page mentions Porphyry's early writings being contradicted."
  },
  "126|Porphyry|De Abstinentia": {
    "bookId": "69906309e7b7642c081dddf5",
    "slug": "de-abstinentia-ab-esu-animalium-porphyry",
    "title": "On Abstinence from Animal Food",
    "pageId": "69906309e7b7642c081dde61",
    "pageNumber": 108,
    "similarity": 0.72,
    "why": "Page discusses wicked powers and apotropaic sacrifices."
  },
  "127|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cf74",
    "pageNumber": 221,
    "similarity": 0.765,
    "why": "The text discusses the oikodespotes and the Spirit."
  },
  "128|Porphyry|De Abstinentia": {
    "bookId": "69906309e7b7642c081dddf5",
    "slug": "de-abstinentia-ab-esu-animalium-porphyry",
    "title": "On Abstinence from Animal Food",
    "pageId": "69906309e7b7642c081ddebb",
    "pageNumber": 198,
    "similarity": 0.764,
    "why": "Page contains the cited Magoi metempsychosis passage."
  },
  "131|Plato|Phaedrus": {
    "bookId": "6953cee877f38f6761be5dd8",
    "slug": "plato-euthyphro-apology-crito-phaedo-phaedrus-plato",
    "title": "Plato Euthyphro, Apology, Crito, Phaedo, Phaedrus",
    "pageId": "6953cee977f38f6761be5fc6",
    "pageNumber": 494,
    "similarity": 0.839,
    "why": "The text covers the soul's chariot allegory."
  },
  "131|Plato|Phaedo": {
    "bookId": "69937767b0a84a57639639fe",
    "slug": "phaedo-plato",
    "title": "Phaedo",
    "pageId": "69937767b0a84a5763963a4c",
    "pageNumber": 78,
    "similarity": 0.861,
    "why": "The text explicitly discusses soul-body separation."
  },
  "131|Synesius of Cyrene|De insomniis": {
    "bookId": "69942bfbb2f6748db4abc883",
    "slug": "de-regno-ad-arcadium-de-insomniis-comm",
    "title": "On Kingship; On Dreams",
    "pageId": "69942bfbb2f6748db4abc902",
    "pageNumber": 127,
    "similarity": 0.805,
    "why": "Margin mentions Hecate and Chaldaean Oracles."
  },
  "132|Origen|Contra Celsum": {
    "bookId": "69942a87045dfc482ad77805",
    "slug": "opera-omnia-xviii-contra-celsum-i-iv-lommatzsch-origen",
    "title": "Complete Works XVIII: Against Celsus I-IV (Lommatzsch)",
    "pageId": "69942a87045dfc482ad778ed",
    "pageNumber": 232,
    "similarity": 0.755,
    "why": "Page discusses luminous body and phantasms."
  },
  "133|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cf03",
    "pageNumber": 108,
    "similarity": 0.797,
    "why": "Page contains Iamblichus Section II, specifically II.6."
  },
  "133|Augustine of Hippo|City of God": {
    "bookId": "699062f5ef12272ffdc8e9d5",
    "slug": "de-civitate-dei-augustine",
    "title": "De Civitate Dei",
    "pageId": "699062f5ef12272ffdc8eac3",
    "pageNumber": 238,
    "similarity": 0.816,
    "why": "The text discusses Porphyry, demons, and magic."
  },
  "136|Proclus|Commentary on Plato's Timaeus": {
    "bookId": "69a5e5e385fa13e734e41894",
    "slug": "procli-opera-grec-1839-proclus",
    "title": "Commentary on Plato's Timaeus",
    "pageId": "69a5e5e385fa13e734e41a70",
    "pageNumber": 476,
    "similarity": 0.794,
    "why": "The text explicitly discusses the spherical ochēma."
  },
  "136|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cefc",
    "pageNumber": 101,
    "similarity": 0.784,
    "why": "Page explicitly discusses II.7 and daemonic hierarchies."
  },
  "138|Proclus|Commentary on Plato's Timaeus": {
    "bookId": "69a5e5e385fa13e734e41894",
    "slug": "procli-opera-grec-1839-proclus",
    "title": "Commentary on Plato's Timaeus",
    "pageId": "69a5e5e385fa13e734e41c34",
    "pageNumber": 928,
    "similarity": 0.773,
    "why": "Page discusses irrational soul, vehicle, and Iamblichus."
  },
  "142|Aristotle|Metaphysics": {
    "bookId": "699388e374305116d72d0502",
    "slug": "aristotle-physics-metaphysics-and-ethics-aristotle",
    "title": "Physics, Metaphysics, and Ethics",
    "pageId": "699388e374305116d72d06d3",
    "pageNumber": 465,
    "similarity": 0.752,
    "why": "The text explicitly discusses Pythagorean number principles."
  },
  "144|Eunapius|Lives of the Sophists": {
    "bookId": "699437c36879ff0184cb7381",
    "slug": "vitae-sophistarum-et-fragmenta-historiarum-sardis",
    "title": "Lives of the Sophists and Fragments of the Histories",
    "pageId": "699437c36879ff0184cb73df",
    "pageNumber": 94,
    "similarity": 0.804,
    "why": "Page describes Sopater's court influence and conspiracy."
  },
  "144|John Lydus|De mensibus": {
    "bookId": "69a9575c65ddd05bbcd3eb47",
    "slug": "de-mensibus-on-the-months-roether",
    "title": "On the Months",
    "pageId": "69a9575c65ddd05bbcd3ebf2",
    "pageNumber": 171,
    "similarity": 0.654,
    "why": "Page mentions Sopater, Constantine, and city founding."
  },
  "151|Anonymous|Testament of Solomon": {
    "bookId": "695936cf3b43cb6630c91ab8",
    "slug": "testament-of-solomon-mccown-critical-edition-attr",
    "title": "Testament of Solomon (McCown Critical Edition)",
    "pageId": "695936d03b43cb6630c91b90",
    "pageNumber": 216,
    "similarity": 0.741,
    "why": "Page contains verses 20.11-16 regarding multiple heavens."
  },
  "160|Origen|Philocalia": {
    "bookId": "6953a54f77f38f6761bcf8a6",
    "slug": "origen-philocalia-greek-ed",
    "title": "Origen Philocalia (Greek)",
    "pageId": "6953a54f77f38f6761bcfab2",
    "pageNumber": 524,
    "similarity": 0.745,
    "why": "The text discusses stars as signs, not causes."
  },
  "162|Plato|Theaetetus": {
    "bookId": "6953ce9577f38f6761be535d",
    "slug": "plato-theaetetus-sophist-plato",
    "title": "Plato: Theaetetus and Sophist",
    "pageId": "6953ce9577f38f6761be53e7",
    "pageNumber": 138,
    "similarity": 0.805,
    "why": "The text explicitly mentions assimilation to God."
  },
  "164|Clement of Alexandria|Stromata": {
    "bookId": "69942a51045dfc482ad766f4",
    "slug": "clemens-alexandrinus-ii-stromata-i-vi-gcs-stahlin-alexandria",
    "title": "Clement of Alexandria II: Stromata I-VI",
    "pageId": "69942a51045dfc482ad76892",
    "pageNumber": 414,
    "similarity": 0.786,
    "why": "The page explicitly quotes the Moses passage."
  },
  "167|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961bb0",
    "pageNumber": 281,
    "similarity": 0.843,
    "why": "The text covers the allegory of sun."
  },
  "167|Plato|Phaedrus": {
    "bookId": "6953cee877f38f6761be5dd8",
    "slug": "plato-euthyphro-apology-crito-phaedo-phaedrus-plato",
    "title": "Plato Euthyphro, Apology, Crito, Phaedo, Phaedrus",
    "pageId": "6953cee977f38f6761be5fcc",
    "pageNumber": 500,
    "similarity": 0.794,
    "why": "The text covers the ascent-myth at 248a-e."
  },
  "167|Anonymous|Codex Theodosianus": {
    "bookId": "69a97a0cdaf647306a73737d",
    "slug": "theodosiani-libri-xvi-vol-1-ii",
    "title": "Theodosian Code, Volume 1",
    "pageId": "69a97a0cdaf647306a73766a",
    "pageNumber": 749,
    "similarity": 0.735,
    "why": "The text explicitly includes CTh.13.3.5."
  },
  "167|Eusebius of Caesarea|Life of Constantine": {
    "bookId": "69ad6a635e7e0803b48e648e",
    "slug": "nicene-and-post-nicene-fathers-series-2-vol-1-eusebius-eds",
    "title": "Nicene and Post-Nicene Fathers, Series 2, Vol. 1 (Eusebius: Church History, Life of Constantine)",
    "pageId": "69ad6a635e7e0803b48e6686",
    "pageNumber": 504,
    "similarity": 0.794,
    "why": "The text explicitly covers chapters 28 and 29."
  },
  "167|Lactantius|De mortibus persecutorum": {
    "bookId": "69af22b6f98f6eff774cd317",
    "slug": "lactantius-opera-omnia-vol-ii-csel-27-lactantius",
    "title": "Complete Works of Lactantius, Vol. II",
    "pageId": "69af22b6f98f6eff774cd472",
    "pageNumber": 347,
    "similarity": 0.79,
    "why": "The text describes Constantine's vision and sign."
  },
  "169|Ammianus Marcellinus|Res Gestae": {
    "bookId": "69af4702b8e08960c7fbbbeb",
    "slug": "ammiani-marcellini-rerum-gestarum-libri-xviii-valesius-1693-marcellinus",
    "title": "The Roman History (Res Gestae)",
    "pageId": "69af4702b8e08960c7fbbe19",
    "pageNumber": 558,
    "similarity": 0.739,
    "why": "Page describes Julian's excessive cattle sacrifices."
  },
  "169|Macrobius|Saturnalia": {
    "bookId": "69942c37b2f6748db4abd178",
    "slug": "in-somnium-scipionis-explanatio-saturnaliorum-libri-vii-censorinus",
    "title": "Commentary on the Dream of Scipio; The Saturnalia; On the Birthday",
    "pageId": "69942c37b2f6748db4abd2b0",
    "pageNumber": 312,
    "similarity": 0.742,
    "why": "Text discusses solar powers and divine conflation."
  },
  "169|Sallustius|On the Gods and the World": {
    "bookId": "69924f515976b55115ffdece",
    "slug": "sallust-on-the-gods-and-the-world-proclus-hymns-taylor",
    "title": "Sallust on the Gods and the World; Proclus Hymns",
    "pageId": "69924f515976b55115ffdf38",
    "pageNumber": 106,
    "similarity": 0.71,
    "why": "Page discusses dæmons punishing souls for guilt."
  },
  "169|Julian|Letters": {
    "bookId": "69ad72e75953f4eff4f330c8",
    "slug": "the-works-of-the-emperor-julian-vol-1-loeb-emperor",
    "title": "The Works of the Emperor Julian, Vol. 1 (Loeb)",
    "pageId": "69ad72e75953f4eff4f33276",
    "pageNumber": 430,
    "similarity": 0.731,
    "why": "Page discusses national gods and Moses' god."
  },
  "172|Augustine of Hippo|City of God": {
    "bookId": "699062f5ef12272ffdc8e9d5",
    "slug": "de-civitate-dei-augustine",
    "title": "De Civitate Dei",
    "pageId": "699062f5ef12272ffdc8e9fa",
    "pageNumber": 37,
    "similarity": 0.755,
    "why": "The text explicitly discusses I.7 and Alaric."
  },
  "172|Orosius|Seven Books of History Against the Pagans": {
    "bookId": "69af2331d510291a0ec78a9e",
    "slug": "orosius-adversus-paganos-historiarum-libri-septem-orosius",
    "title": "Seven Books of History Against the Pagans",
    "pageId": "69af2331d510291a0ec78be4",
    "pageNumber": 326,
    "similarity": 0.677,
    "why": "The text explicitly discusses Alaric's selective clemency."
  },
  "173|John Malalas|Chronographia": {
    "bookId": "69938d9dd5a98fd66f42dc60",
    "slug": "chronographia-dindorf-cshb-edition-malalas",
    "title": "Chronicle",
    "pageId": "69938d9dd5a98fd66f42df19",
    "pageNumber": 697,
    "similarity": 0.754,
    "why": "The page explicitly discusses Hypatia's murder."
  },
  "173|Socrates of Constantinople|Ecclesiastical History": {
    "bookId": "69b21dca94025df5d2909ff2",
    "slug": "socrates-scholasticus-ecclesiastical-history-greek-hussey-hussey",
    "title": "Ecclesiastical History",
    "pageId": "69b21dca94025df5d290a004",
    "pageNumber": 18,
    "similarity": 0.799,
    "why": "Page lists chapters 7.7, 7.13, 7.14, 7.15."
  },
  "174|Anonymous|Codex Theodosianus": {
    "bookId": "69a97a0cdaf647306a73737d",
    "slug": "theodosiani-libri-xvi-vol-1-ii",
    "title": "Theodosian Code, Volume 1",
    "pageId": "69a97a0cdaf647306a737705",
    "pageNumber": 904,
    "similarity": 0.839,
    "why": "The text explicitly contains CTh 16.10.10-12."
  },
  "174|Socrates of Constantinople|Ecclesiastical History": {
    "bookId": "69b21dca94025df5d2909ff2",
    "slug": "socrates-scholasticus-ecclesiastical-history-greek-hussey-hussey",
    "title": "Ecclesiastical History",
    "pageId": "69b21dca94025df5d290a063",
    "pageNumber": 113,
    "similarity": 0.597,
    "why": "The text explicitly contains chapter 15."
  },
  "180|Plotinus|Enneads": {
    "bookId": "69a5e5d91d73f9668388ef2b",
    "slug": "plotini-enneades-13th-c-copy-a-plotinus",
    "title": "The Enneads",
    "pageId": "69a5e5d91d73f9668388f177",
    "pageNumber": 588,
    "similarity": 0.612,
    "why": "The text contains the cited passage V.3.14."
  },
  "180|Augustine of Hippo|Epistulae": {
    "bookId": "69ac9bdedc7bbeb9206212f1",
    "slug": "epistulae-hippo",
    "title": "Letters (Epistulae)",
    "pageId": "69ac9bdedc7bbeb92062130b",
    "pageNumber": 26,
    "similarity": 0.742,
    "why": "The text explicitly discusses the physician-argument."
  },
  "183|Marinus of Neapolis|Life of Proclus": {
    "bookId": "6952ca6e77f38f6761bc3fb2",
    "slug": "life-of-proclus-by-marinus-neapolis",
    "title": "The Life of Proclus",
    "pageId": "6952ca6e77f38f6761bc3ff3",
    "pageNumber": 65,
    "similarity": 0.731,
    "why": "Page 12 discusses students and teaching."
  },
  "184|Hierocles of Alexandria|Commentary on the Golden Verses of Pythagoras": {
    "bookId": "699389a6ce15387065947dc0",
    "slug": "hieroclis-expositio-versuum-pythagorae-qui-aurei-dicuntur-trismegistus",
    "title": "Hieroclis Expositio versuum Pythagorae qui aurei dicuntur . Hermes Trismegistus . Adde etiam Hermes Trismegistus, Apuleio interprete",
    "pageId": "699389a7ce15387065947e7f",
    "pageNumber": 191,
    "similarity": 0.772,
    "why": "Page discusses purification of the soul's vehicle."
  },
  "186|Proclus|Commentary on Plato's Timaeus": {
    "bookId": "69a5e5e385fa13e734e41894",
    "slug": "procli-opera-grec-1839-proclus",
    "title": "Commentary on Plato's Timaeus",
    "pageId": "69a5e5e385fa13e734e418a5",
    "pageNumber": 17,
    "similarity": 0.762,
    "why": "Page discusses the Creator and creative Intellect."
  },
  "186|Apuleius|Metamorphoses": {
    "bookId": "69af21d07c27d4b637feddd1",
    "slug": "metamorphoseon-libri-xi-apuleius",
    "title": "The Golden Ass (Metamorphoses)",
    "pageId": "69af21d07c27d4b637fedf28",
    "pageNumber": 343,
    "similarity": 0.673,
    "why": "The text explicitly mentions the Pythagorean bath."
  },
  "186|Plato|Philebus": {
    "bookId": "69b21d42ddb4fa7c305b4693",
    "slug": "platonis-opera-quae-extant-vol-2-stephanus-plato",
    "title": "The Works of Plato, Vol. 2 (Stephanus edition)",
    "pageId": "69b21d42ddb4fa7c305b46b0",
    "pageNumber": 29,
    "similarity": 0.599,
    "why": "Page contains the 16c-d discussion of One/Many."
  },
  "187|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961b0d",
    "pageNumber": 118,
    "similarity": 0.791,
    "why": "The text contains the passage at 378d."
  },
  "189|Aristotle|Metaphysics": {
    "bookId": "699388e374305116d72d0502",
    "slug": "aristotle-physics-metaphysics-and-ethics-aristotle",
    "title": "Physics, Metaphysics, and Ethics",
    "pageId": "699388e374305116d72d06d9",
    "pageNumber": 471,
    "similarity": 0.761,
    "why": "The text discusses arguments regarding the Forms."
  },
  "190|John Malalas|Chronographia": {
    "bookId": "69938d9dd5a98fd66f42dc60",
    "slug": "chronographia-dindorf-cshb-edition-malalas",
    "title": "Chronicle",
    "pageId": "69938d9dd5a98fd66f42de74",
    "pageNumber": 532,
    "similarity": 0.675,
    "why": "The text explicitly mentions the Athenian edict."
  },
  "192|Homer|Iliad": {
    "bookId": "69e7478285f786e884a487d4",
    "slug": "homeri-ilias-homer",
    "title": "Ὁμήρου Ἰλιάς (Homeri Ilias)",
    "pageId": "69e7478385f786e884a488f5",
    "pageNumber": 289,
    "similarity": 0.814,
    "why": "The text explicitly contains the golden chain."
  },
  "195|Agathias|Histories": {
    "bookId": "6953a55277f38f6761bcfb62",
    "slug": "corpus-byzantinae-vol-14-ed",
    "title": "Corpus Byzantinae Vol. 14",
    "pageId": "6953a55277f38f6761bcfbef",
    "pageNumber": 141,
    "similarity": 0.675,
    "why": "The page contains the cited passage text."
  },
  "195|Zacharias Scholasticus|Life of Severus": {
    "bookId": "69a99d0a510aaf87d0635bfc",
    "slug": "patrologia-orientalis-tome-ii-inc-vie-de-severe-scholasticus",
    "title": "The Life of Severus",
    "pageId": "69a99d0a510aaf87d0635c12",
    "pageNumber": 22,
    "similarity": 0.736,
    "why": "The text explicitly defines and mentions Philoponoi."
  },
  "204|Plotinus|Enneads": {
    "bookId": "69a5e5d91d73f9668388ef2b",
    "slug": "plotini-enneades-13th-c-copy-a-plotinus",
    "title": "The Enneads",
    "pageId": "69a5e5d91d73f9668388f1b7",
    "pageNumber": 652,
    "similarity": 0.787,
    "why": "Text mentions entering sanctuary and not speaking."
  },
  "237|Anonymous|Corpus Hermeticum": {
    "bookId": "69b51e1fcf111105c42975fb",
    "slug": "divinvs-pymander-hermetis-mercvrii-trismegisti-opvs-vere-hermes",
    "title": "The Divine Pymander of Hermes Mercurius Trismegistus",
    "pageId": "69b51e1fcf111105c4297623",
    "pageNumber": 40,
    "similarity": 0.667,
    "why": "The text explicitly lists the twelve tormentors."
  },
  "237|Porphyry|De Abstinentia": {
    "bookId": "69906309e7b7642c081dddf5",
    "slug": "de-abstinentia-ab-esu-animalium-porphyry",
    "title": "On Abstinence from Animal Food",
    "pageId": "69906309e7b7642c081dde60",
    "pageNumber": 107,
    "similarity": 0.795,
    "why": "Text discusses daemons consuming sacrifices and vapors."
  },
  "238|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cf6c",
    "pageNumber": 213,
    "similarity": 0.68,
    "why": "Page explicitly mentions Bitys and Hermes' teachings."
  },
  "238|Anonymous|Sibylline Oracles": {
    "bookId": "6953113877f38f6761bcc0d9",
    "slug": "sibylline-oracles-greek-ed",
    "title": "Sibylline Oracles (Greek)",
    "pageId": "695906f695a91542b28c0b6e",
    "pageNumber": 409,
    "similarity": 0.699,
    "why": "The text explicitly discusses the Adam etymology."
  },
  "248|Ammianus Marcellinus|Res Gestae": {
    "bookId": "69af4702b8e08960c7fbbbeb",
    "slug": "ammiani-marcellini-rerum-gestarum-libri-xviii-valesius-1693-marcellinus",
    "title": "The Roman History (Res Gestae)",
    "pageId": "69af4702b8e08960c7fbbe14",
    "pageNumber": 553,
    "similarity": 0.788,
    "why": "The text describes Julian's death and life."
  },
  "266|Diogenes Laërtius|Lives of the Eminent Philosophers": {
    "bookId": "6993882874305116d72cf9f3",
    "slug": "pal-gr-182-laertius",
    "title": "Pal.gr.182",
    "pageId": "6993882874305116d72cfb6d",
    "pageNumber": 378,
    "similarity": 0.722,
    "why": "Text discusses soul, pneuma, and perception."
  },
  "267|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961c46",
    "pageNumber": 431,
    "similarity": 0.764,
    "why": "The text describes the rainbow-colored pillar."
  },
  "267|Marcus Tullius Cicero|Tusculanae Disputationes": {
    "bookId": "69dbc97b1040d1d5e20a3743",
    "slug": "tusculanae-disputationes-with-anonymous-commentary-additions-cicero",
    "title": "Tusculan Disputations",
    "pageId": "69dbc97b1040d1d5e20a3765",
    "pageNumber": 34,
    "similarity": 0.717,
    "why": "The text explicitly quotes Plato's Apology passage."
  },
  "270|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961bb2",
    "pageNumber": 283,
    "similarity": 0.836,
    "why": "The text explicitly mentions the Good beyond ousia."
  },
  "270|Macrobius|Saturnalia": {
    "bookId": "69942c37b2f6748db4abd178",
    "slug": "in-somnium-scipionis-explanatio-saturnaliorum-libri-vii-censorinus",
    "title": "Commentary on the Dream of Scipio; The Saturnalia; On the Birthday",
    "pageId": "69942c37b2f6748db4abd25a",
    "pageNumber": 226,
    "similarity": 0.658,
    "why": "The text explicitly discusses Timaeus and Socrates."
  },
  "270|Plato|Gorgias": {
    "bookId": "69a5e5f385fa13e734e41e1f",
    "slug": "platonis-dialogi-xxiv-the-clarke-plato-plato",
    "title": "Twenty-four Dialogues of Plato",
    "pageId": "69a5e5f385fa13e734e41e9b",
    "pageNumber": 124,
    "similarity": 0.744,
    "why": "The text describes the afterlife judgment myth."
  },
  "274|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961ae6",
    "pageNumber": 79,
    "similarity": 0.736,
    "why": "The text mentions begging priests and seers."
  },
  "274|Iamblichus|De mysteriis": {
    "bookId": "6991d8e18c1030b12444ce97",
    "slug": "de-mysteriis-liber-greek-latin-edition-gale",
    "title": "On the Mysteries (De Mysteriis)",
    "pageId": "6991d8e18c1030b12444cf1c",
    "pageNumber": 133,
    "similarity": 0.73,
    "why": "The page contains the cited III 11 passage."
  },
  "280|Proclus|Commentary on Plato's Timaeus": {
    "bookId": "69a5e5e385fa13e734e41894",
    "slug": "procli-opera-grec-1839-proclus",
    "title": "Commentary on Plato's Timaeus",
    "pageId": "69a5e5e385fa13e734e41926",
    "pageNumber": 146,
    "similarity": 0.796,
    "why": "Page discusses the heptad and monad for Athena."
  },
  "302|Plato|Republic": {
    "bookId": "699376d2b0a84a5763961a97",
    "slug": "platonis-opera-republic-timaeus-critias-plato",
    "title": "Works of Plato (Republic, Timaeus, Critias)",
    "pageId": "699376d2b0a84a5763961bb2",
    "pageNumber": 283,
    "similarity": 0.811,
    "why": "The text explicitly discusses the Good beyond ousia."
  },
  "323|Pliny the Elder|Natural History": {
    "bookId": "69afd0df775a23a98ee93a30",
    "slug": "historia-naturalis-elder",
    "title": "Natural History",
    "pageId": "69afd0df775a23a98ee93ad0",
    "pageNumber": 160,
    "similarity": 0.689,
    "why": "The text explicitly mentions Aeschylus' death."
  }
};
